// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/validate"
)

func decodeAPI4meAppPostResponse(resp *http.Response) (res API4meAppPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &API4meAppPostOK{}, nil
	case 401:
		// Code 401.
		return &API4meAppPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &API4meAppPostForbidden{}, nil
	case 405:
		// Code 405.
		return &API4meAppPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPI4meConfigPostResponse(resp *http.Response) (res *API4meConfigPostOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &API4meConfigPostOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIAuthenticatePostResponse(resp *http.Response) (res APIAuthenticatePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIAuthenticatePostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIAuthenticatePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIAuthenticatePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIAuthenticatePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIRefreshPostResponse(resp *http.Response) (res *APIRefreshPostOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIRefreshPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ComponentsGetResponse(resp *http.Response) (res APIV1ComponentsGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV1ComponentsGetOK{}, nil
	case 401:
		// Code 401.
		return &APIV1ComponentsGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ComponentsGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1ComponentsGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ComponentsPostResponse(resp *http.Response) (res APIV1ComponentsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV1ComponentsPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV1ComponentsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ComponentsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1ComponentsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1ComponentsPutResponse(resp *http.Response) (res APIV1ComponentsPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV1ComponentsPutOK{}, nil
	case 401:
		// Code 401.
		return &APIV1ComponentsPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1ComponentsPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1ComponentsPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1IncidentsGetResponse(resp *http.Response) (res APIV1IncidentsGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV1IncidentsGetOK{}, nil
	case 401:
		// Code 401.
		return &APIV1IncidentsGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1IncidentsGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1IncidentsGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1IncidentsUpdatesPostResponse(resp *http.Response) (res APIV1IncidentsUpdatesPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1IncidentsUpdatesPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV1IncidentsUpdatesPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1IncidentsUpdatesPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1IncidentsUpdatesPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV1TokenPostResponse(resp *http.Response) (res APIV1TokenPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV1TokenPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV1TokenPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV1TokenPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV1TokenPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4BulkgroupactionDeleteResponse(resp *http.Response) (res APIV4BulkgroupactionDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4BulkgroupactionDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4BulkgroupactionDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4BulkgroupactionDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4BulkgroupactionDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4BulkgroupactionPostResponse(resp *http.Response) (res APIV4BulkgroupactionPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4BulkgroupactionPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4BulkgroupactionPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4BulkgroupactionPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4BulkgroupactionPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4BulkgroupsDeleteResponse(resp *http.Response) (res APIV4BulkgroupsDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4BulkgroupsDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4BulkgroupsDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4BulkgroupsDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4BulkgroupsDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4BulkgroupsPostResponse(resp *http.Response) (res APIV4BulkgroupsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4BulkgroupsPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4BulkgroupsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4BulkgroupsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4BulkgroupsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentDeleteResponse(resp *http.Response) (res APIV4ComponentDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4ComponentDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4ComponentDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentIDGetResponse(resp *http.Response) (res APIV4ComponentIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentIDHistoryGetResponse(resp *http.Response) (res APIV4ComponentIDHistoryGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentIDHistoryGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentIDHistoryGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentIDHistoryGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentIDHistoryGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentIDUptimeGetResponse(resp *http.Response) (res APIV4ComponentIDUptimeGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentIDUptimeGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentIDUptimeGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentIDUptimeGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentIDUptimeGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentMovePostResponse(resp *http.Response) (res APIV4ComponentMovePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentMovePostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentMovePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentMovePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentMovePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentPostResponse(resp *http.Response) (res APIV4ComponentPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentPutResponse(resp *http.Response) (res APIV4ComponentPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentPutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentSetstatusPostResponse(resp *http.Response) (res APIV4ComponentSetstatusPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4ComponentSetstatusPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4ComponentSetstatusPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentSetstatusPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentSetstatusPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsGetResponse(resp *http.Response) (res APIV4ComponentsGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsHistoryGetResponse(resp *http.Response) (res APIV4ComponentsHistoryGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsHistoryGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsHistoryGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsHistoryGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsHistoryGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsHistoryGroupIDGetResponse(resp *http.Response) (res APIV4ComponentsHistoryGroupIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsHistoryGroupIDGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsHistoryGroupIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsHistoryGroupIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsHistoryGroupIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsHistoryIncidentIDGetResponse(resp *http.Response) (res APIV4ComponentsHistoryIncidentIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsHistoryIncidentIDGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsHistoryIncidentIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsHistoryIncidentIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsHistoryIncidentIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsPostResponse(resp *http.Response) (res APIV4ComponentsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ComponentsUptimeGetResponse(resp *http.Response) (res APIV4ComponentsUptimeGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ComponentsUptimeGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ComponentsUptimeGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ComponentsUptimeGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ComponentsUptimeGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ContenttemplateGetResponse(resp *http.Response) (res APIV4ContenttemplateGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ContenttemplateGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ContenttemplateGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ContenttemplateGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ContenttemplateGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ContenttemplateIDDeleteResponse(resp *http.Response) (res APIV4ContenttemplateIDDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4ContenttemplateIDDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4ContenttemplateIDDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ContenttemplateIDDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ContenttemplateIDDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ContenttemplateIDGetResponse(resp *http.Response) (res APIV4ContenttemplateIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ContenttemplateIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ContenttemplateIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ContenttemplateIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ContenttemplateIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ContenttemplatePostResponse(resp *http.Response) (res APIV4ContenttemplatePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ContenttemplatePostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ContenttemplatePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ContenttemplatePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ContenttemplatePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4ContenttemplatePutResponse(resp *http.Response) (res APIV4ContenttemplatePutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4ContenttemplatePutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4ContenttemplatePutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4ContenttemplatePutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4ContenttemplatePutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupIDDeleteResponse(resp *http.Response) (res APIV4GroupIDDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupIDDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupIDDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupIDDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupIDDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupIDGetResponse(resp *http.Response) (res APIV4GroupIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupPostResponse(resp *http.Response) (res APIV4GroupPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupPutResponse(resp *http.Response) (res APIV4GroupPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupPutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupactionDeleteResponse(resp *http.Response) (res APIV4GroupactionDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupactionDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupactionDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupactionDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupactionDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupactionPostResponse(resp *http.Response) (res APIV4GroupactionPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupactionPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupactionPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupactionPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupactionPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupcomponentsIDGetResponse(resp *http.Response) (res APIV4GroupcomponentsIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupcomponentsIDGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupcomponentsIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupcomponentsIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupcomponentsIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupcomponentsIDPutResponse(resp *http.Response) (res APIV4GroupcomponentsIDPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupcomponentsIDPutOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupcomponentsIDPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupcomponentsIDPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupcomponentsIDPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupincidentsIDGetResponse(resp *http.Response) (res APIV4GroupincidentsIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupincidentsIDGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupincidentsIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupincidentsIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupincidentsIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupincidentsIDPutResponse(resp *http.Response) (res APIV4GroupincidentsIDPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupincidentsIDPutOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupincidentsIDPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupincidentsIDPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupincidentsIDPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupsPostResponse(resp *http.Response) (res APIV4GroupsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupsPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupsubscriptionsIDGetResponse(resp *http.Response) (res APIV4GroupsubscriptionsIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4GroupsubscriptionsIDGetOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4GroupsubscriptionsIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupsubscriptionsIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupsubscriptionsIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4GroupsubscriptionsIDPutResponse(resp *http.Response) (res APIV4GroupsubscriptionsIDPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4GroupsubscriptionsIDPutOK{}, nil
	case 401:
		// Code 401.
		return &APIV4GroupsubscriptionsIDPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4GroupsubscriptionsIDPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4GroupsubscriptionsIDPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentIDDeleteResponse(resp *http.Response) (res APIV4IncidentIDDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4IncidentIDDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4IncidentIDDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentIDDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentIDDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentIDGetResponse(resp *http.Response) (res APIV4IncidentIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4IncidentIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4IncidentIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentPostResponse(resp *http.Response) (res APIV4IncidentPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4IncidentPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4IncidentPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentPutResponse(resp *http.Response) (res APIV4IncidentPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4IncidentPutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4IncidentPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentQueuePostResponse(resp *http.Response) (res APIV4IncidentQueuePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4IncidentQueuePostOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4IncidentQueuePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentQueuePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentQueuePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentsPostResponse(resp *http.Response) (res APIV4IncidentsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4IncidentsPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4IncidentsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4IncidentupdateIDDeleteResponse(resp *http.Response) (res APIV4IncidentupdateIDDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4IncidentupdateIDDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4IncidentupdateIDDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4IncidentupdateIDDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4IncidentupdateIDDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4MetricDeleteResponse(resp *http.Response) (res APIV4MetricDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4MetricDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4MetricDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4MetricDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4MetricDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4MetricPostResponse(resp *http.Response) (res APIV4MetricPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4MetricPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4MetricPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4MetricPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4MetricPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4MetricsPostResponse(resp *http.Response) (res APIV4MetricsPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4MetricsPostOKApplicationJSON
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4MetricsPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4MetricsPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4MetricsPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PageIDGetResponse(resp *http.Response) (res APIV4PageIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PageIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PageIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PageIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PageIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PagePostResponse(resp *http.Response) (res APIV4PagePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PagePostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PagePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PagePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PagePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PagePutResponse(resp *http.Response) (res APIV4PagePutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PagePutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PagePutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PagePutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PagePutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PageStatusGetResponse(resp *http.Response) (res APIV4PageStatusGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PageStatusGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PageStatusGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PageStatusGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PageStatusGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PagesPostResponse(resp *http.Response) (res APIV4PagesPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PagesPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PagesPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PagesPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PagesPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4PublicstatuspagesGetResponse(resp *http.Response) (res APIV4PublicstatuspagesGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4PublicstatuspagesGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4PublicstatuspagesGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4PublicstatuspagesGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4PublicstatuspagesGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscriberIDDeleteResponse(resp *http.Response) (res APIV4SubscriberIDDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4SubscriberIDDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4SubscriberIDDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscriberIDDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscriberIDDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscriberIDGetResponse(resp *http.Response) (res APIV4SubscriberIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4SubscriberIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4SubscriberIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscriberIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscriberIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscriberIDReinvitePostResponse(resp *http.Response) (res APIV4SubscriberIDReinvitePostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4SubscriberIDReinvitePostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4SubscriberIDReinvitePostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscriberIDReinvitePostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscriberIDReinvitePostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscriberPostResponse(resp *http.Response) (res APIV4SubscriberPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4SubscriberPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4SubscriberPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscriberPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscriberPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscriberPutResponse(resp *http.Response) (res APIV4SubscriberPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4SubscriberPutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4SubscriberPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscriberPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscriberPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscribersPostResponse(resp *http.Response) (res APIV4SubscribersPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4SubscribersPostOK{}, nil
	case 401:
		// Code 401.
		return &APIV4SubscribersPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscribersPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscribersPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscribersPutResponse(resp *http.Response) (res APIV4SubscribersPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4SubscribersPutOK{}, nil
	case 401:
		// Code 401.
		return &APIV4SubscribersPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscribersPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscribersPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4SubscribersSearchPostResponse(resp *http.Response) (res APIV4SubscribersSearchPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4SubscribersSearchPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4SubscribersSearchPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4SubscribersSearchPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4SubscribersSearchPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4UserDeleteResponse(resp *http.Response) (res APIV4UserDeleteRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &APIV4UserDeleteOK{}, nil
	case 401:
		// Code 401.
		return &APIV4UserDeleteUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4UserDeleteForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4UserDeleteMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4UserIDGetResponse(resp *http.Response) (res APIV4UserIDGetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4UserIDGetOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4UserIDGetUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4UserIDGetForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4UserIDGetMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4UserPostResponse(resp *http.Response) (res APIV4UserPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4UserPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4UserPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4UserPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4UserPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4UserPutResponse(resp *http.Response) (res APIV4UserPutRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4UserPutOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4UserPutUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4UserPutForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4UserPutMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeAPIV4UsersPostResponse(resp *http.Response) (res APIV4UsersPostRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response APIV4UsersPostOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			// Validate response.
			if err := func() error {
				if err := response.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return res, errors.Wrap(err, "validate")
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		return &APIV4UsersPostUnauthorized{}, nil
	case 403:
		// Code 403.
		return &APIV4UsersPostForbidden{}, nil
	case 405:
		// Code 405.
		return &APIV4UsersPostMethodNotAllowed{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePostApiv4imageuploadResponse(resp *http.Response) (res PostApiv4imageuploadRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response PostApiv4imageuploadOK
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 401:
		// Code 401.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response PostApiv4imageuploadUnauthorized
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 422:
		// Code 422.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response PostApiv4imageuploadUnprocessableEntity
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
