// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn1AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn6AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn7AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn11AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn13AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type",
		"POST":   "Authorization,Content-Type",
	}
	rn15AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type",
		"POST":   "Authorization,Content-Type",
	}
	rn17AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"POST":   "Authorization,Content-Type",
		"PUT":    "Authorization,Content-Type",
	}
	rn23AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn24AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn19AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn20AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn22AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn25AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn26AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn28AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn31AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn33AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn35AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn37AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn40AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn39AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn41AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type",
		"POST":   "Authorization,Content-Type",
	}
	rn43AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn45AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn46AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn48AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn76AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn51AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn52AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn50AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn53AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn55AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
	}
	rn56AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type",
		"POST":   "Authorization,Content-Type",
	}
	rn57AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn60AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn61AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn59AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn62AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn64AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn68AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn66AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn67AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn69AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
		"PUT":  "Authorization,Content-Type",
	}
	rn70AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn71AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"POST":   "Authorization,Content-Type",
		"PUT":    "Authorization,Content-Type",
	}
	rn73AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn74AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '4': // Prefix: "4me/"

				if l := len("4me/"); len(elem) >= l && elem[0:l] == "4me/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "app"

					if l := len("app"); len(elem) >= l && elem[0:l] == "app" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleAPI4meAppPostRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn1AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'c': // Prefix: "config"

					if l := len("config"); len(elem) >= l && elem[0:l] == "config" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleAPI4meConfigPostRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn3AllowedHeaders,
								acceptPost:     "application/*+json,application/json,application/octet-stream,text/json,text/plain",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'a': // Prefix: "authenticate"

				if l := len("authenticate"); len(elem) >= l && elem[0:l] == "authenticate" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleAPIAuthenticatePostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn5AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'r': // Prefix: "refresh"

				if l := len("refresh"); len(elem) >= l && elem[0:l] == "refresh" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleAPIRefreshPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "POST",
							allowedHeaders: rn6AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '1': // Prefix: "1/"

					if l := len("1/"); len(elem) >= l && elem[0:l] == "1/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "components"

						if l := len("components"); len(elem) >= l && elem[0:l] == "components" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAPIV1ComponentsGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleAPIV1ComponentsPostRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleAPIV1ComponentsPutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST,PUT",
									allowedHeaders: rn7AllowedHeaders,
									acceptPost:     "application/x-www-form-urlencoded",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'i': // Prefix: "incidents"

						if l := len("incidents"); len(elem) >= l && elem[0:l] == "incidents" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleAPIV1IncidentsGetRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn9AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/updates"

							if l := len("/updates"); len(elem) >= l && elem[0:l] == "/updates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAPIV1IncidentsUpdatesPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn10AllowedHeaders,
										acceptPost:     "application/x-www-form-urlencoded",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 't': // Prefix: "token"

						if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleAPIV1TokenPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn11AllowedHeaders,
									acceptPost:     "application/x-www-form-urlencoded",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case '4': // Prefix: "4/"

					if l := len("4/"); len(elem) >= l && elem[0:l] == "4/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "bulkgroup"

						if l := len("bulkgroup"); len(elem) >= l && elem[0:l] == "bulkgroup" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "action"

							if l := len("action"); len(elem) >= l && elem[0:l] == "action" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleAPIV4BulkgroupactionDeleteRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleAPIV4BulkgroupactionPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,POST",
										allowedHeaders: rn13AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleAPIV4BulkgroupsDeleteRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleAPIV4BulkgroupsPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,POST",
										allowedHeaders: rn15AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'c': // Prefix: "co"

						if l := len("co"); len(elem) >= l && elem[0:l] == "co" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'm': // Prefix: "mponent"

							if l := len("mponent"); len(elem) >= l && elem[0:l] == "mponent" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleAPIV4ComponentDeleteRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleAPIV4ComponentPostRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4ComponentPutRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,POST,PUT",
										allowedHeaders: rn17AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'm': // Prefix: "move"
									origElem := elem
									if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleAPIV4ComponentMovePostRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn23AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								case 's': // Prefix: "setstatus"
									origElem := elem
									if l := len("setstatus"); len(elem) >= l && elem[0:l] == "setstatus" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleAPIV4ComponentSetstatusPostRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn24AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								}
								// Param: "id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[0] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleAPIV4ComponentIDGetRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn19AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'h': // Prefix: "history"

										if l := len("history"); len(elem) >= l && elem[0:l] == "history" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleAPIV4ComponentIDHistoryGetRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn20AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									case 'u': // Prefix: "uptime"

										if l := len("uptime"); len(elem) >= l && elem[0:l] == "uptime" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleAPIV4ComponentIDUptimeGetRequest([1]string{
													args[0],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn22AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleAPIV4ComponentsGetRequest([0]string{}, elemIsEscaped, w, r)
									case "POST":
										s.handleAPIV4ComponentsPostRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn25AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'h': // Prefix: "history"

										if l := len("history"); len(elem) >= l && elem[0:l] == "history" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleAPIV4ComponentsHistoryGetRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn26AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'g': // Prefix: "group/"

												if l := len("group/"); len(elem) >= l && elem[0:l] == "group/" {
													elem = elem[l:]
												} else {
													break
												}

												// Param: "id"
												// Leaf parameter, slashes are prohibited
												idx := strings.IndexByte(elem, '/')
												if idx >= 0 {
													break
												}
												args[0] = elem
												elem = ""

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "GET":
														s.handleAPIV4ComponentsHistoryGroupIDGetRequest([1]string{
															args[0],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "GET",
															allowedHeaders: rn28AllowedHeaders,
															acceptPost:     "",
															acceptPatch:    "",
														})
													}

													return
												}

											case 'i': // Prefix: "incident/"

												if l := len("incident/"); len(elem) >= l && elem[0:l] == "incident/" {
													elem = elem[l:]
												} else {
													break
												}

												// Param: "id"
												// Leaf parameter, slashes are prohibited
												idx := strings.IndexByte(elem, '/')
												if idx >= 0 {
													break
												}
												args[0] = elem
												elem = ""

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "GET":
														s.handleAPIV4ComponentsHistoryIncidentIDGetRequest([1]string{
															args[0],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "GET",
															allowedHeaders: rn31AllowedHeaders,
															acceptPost:     "",
															acceptPatch:    "",
														})
													}

													return
												}

											}

										}

									case 'u': // Prefix: "uptime"

										if l := len("uptime"); len(elem) >= l && elem[0:l] == "uptime" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleAPIV4ComponentsUptimeGetRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn33AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							}

						case 'n': // Prefix: "ntenttemplate"

							if l := len("ntenttemplate"); len(elem) >= l && elem[0:l] == "ntenttemplate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleAPIV4ContenttemplateGetRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleAPIV4ContenttemplatePostRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4ContenttemplatePutRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST,PUT",
										allowedHeaders: rn35AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleAPIV4ContenttemplateIDDeleteRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleAPIV4ContenttemplateIDGetRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,GET",
											allowedHeaders: rn37AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'g': // Prefix: "group"

						if l := len("group"); len(elem) >= l && elem[0:l] == "group" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "POST":
								s.handleAPIV4GroupPostRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleAPIV4GroupPutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST,PUT",
									allowedHeaders: rn40AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleAPIV4GroupIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleAPIV4GroupIDGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET",
										allowedHeaders: rn39AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'a': // Prefix: "action"

							if l := len("action"); len(elem) >= l && elem[0:l] == "action" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleAPIV4GroupactionDeleteRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleAPIV4GroupactionPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,POST",
										allowedHeaders: rn41AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'c': // Prefix: "components/"

							if l := len("components/"); len(elem) >= l && elem[0:l] == "components/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleAPIV4GroupcomponentsIDGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4GroupcomponentsIDPutRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,PUT",
										allowedHeaders: rn43AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'i': // Prefix: "incidents/"

							if l := len("incidents/"); len(elem) >= l && elem[0:l] == "incidents/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleAPIV4GroupincidentsIDGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4GroupincidentsIDPutRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,PUT",
										allowedHeaders: rn45AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleAPIV4GroupsPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn46AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case 'u': // Prefix: "ubscriptions/"

								if l := len("ubscriptions/"); len(elem) >= l && elem[0:l] == "ubscriptions/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleAPIV4GroupsubscriptionsIDGetRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "PUT":
										s.handleAPIV4GroupsubscriptionsIDPutRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,PUT",
											allowedHeaders: rn48AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'i': // Prefix: "i"

						if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'm': // Prefix: "mage/upload"

							if l := len("mage/upload"); len(elem) >= l && elem[0:l] == "mage/upload" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handlePostApiv4imageuploadRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn76AllowedHeaders,
										acceptPost:     "multipart/form-data",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'n': // Prefix: "ncident"

							if l := len("ncident"); len(elem) >= l && elem[0:l] == "ncident" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleAPIV4IncidentPostRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4IncidentPutRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST,PUT",
										allowedHeaders: rn51AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'q': // Prefix: "queue"
									origElem := elem
									if l := len("queue"); len(elem) >= l && elem[0:l] == "queue" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleAPIV4IncidentQueuePostRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn52AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								}
								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleAPIV4IncidentIDDeleteRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleAPIV4IncidentIDGetRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,GET",
											allowedHeaders: rn50AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAPIV4IncidentsPostRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn53AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'u': // Prefix: "update/"

								if l := len("update/"); len(elem) >= l && elem[0:l] == "update/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleAPIV4IncidentupdateIDDeleteRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE",
											allowedHeaders: rn55AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'm': // Prefix: "metric"

						if l := len("metric"); len(elem) >= l && elem[0:l] == "metric" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleAPIV4MetricDeleteRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleAPIV4MetricPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,POST",
									allowedHeaders: rn56AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAPIV4MetricsPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn57AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'p': // Prefix: "p"

						if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "age"

							if l := len("age"); len(elem) >= l && elem[0:l] == "age" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleAPIV4PagePostRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4PagePutRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST,PUT",
										allowedHeaders: rn60AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 's': // Prefix: "status"
									origElem := elem
									if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleAPIV4PageStatusGetRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn61AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								}
								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleAPIV4PageIDGetRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn59AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAPIV4PagesPostRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn62AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'u': // Prefix: "ublicstatuspages"

							if l := len("ublicstatuspages"); len(elem) >= l && elem[0:l] == "ublicstatuspages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleAPIV4PublicstatuspagesGetRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn64AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 's': // Prefix: "subscriber"

						if l := len("subscriber"); len(elem) >= l && elem[0:l] == "subscriber" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "POST":
								s.handleAPIV4SubscriberPostRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleAPIV4SubscriberPutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST,PUT",
									allowedHeaders: rn68AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleAPIV4SubscriberIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleAPIV4SubscriberIDGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET",
										allowedHeaders: rn66AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/reinvite"

								if l := len("/reinvite"); len(elem) >= l && elem[0:l] == "/reinvite" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAPIV4SubscriberIDReinvitePostRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn67AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleAPIV4SubscribersPostRequest([0]string{}, elemIsEscaped, w, r)
								case "PUT":
									s.handleAPIV4SubscribersPutRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST,PUT",
										allowedHeaders: rn69AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/search"

								if l := len("/search"); len(elem) >= l && elem[0:l] == "/search" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAPIV4SubscribersSearchPostRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn70AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'u': // Prefix: "user"

						if l := len("user"); len(elem) >= l && elem[0:l] == "user" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleAPIV4UserDeleteRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleAPIV4UserPostRequest([0]string{}, elemIsEscaped, w, r)
							case "PUT":
								s.handleAPIV4UserPutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,POST,PUT",
									allowedHeaders: rn71AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleAPIV4UserIDGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn73AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAPIV4UsersPostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn74AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/"

			if l := len("/api/"); len(elem) >= l && elem[0:l] == "/api/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '4': // Prefix: "4me/"

				if l := len("4me/"); len(elem) >= l && elem[0:l] == "4me/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "app"

					if l := len("app"); len(elem) >= l && elem[0:l] == "app" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = API4meAppPostOperation
							r.summary = ""
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/api/4me/app"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'c': // Prefix: "config"

					if l := len("config"); len(elem) >= l && elem[0:l] == "config" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = API4meConfigPostOperation
							r.summary = ""
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/api/4me/config"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'a': // Prefix: "authenticate"

				if l := len("authenticate"); len(elem) >= l && elem[0:l] == "authenticate" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = APIAuthenticatePostOperation
						r.summary = "Get Token"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/api/authenticate"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'r': // Prefix: "refresh"

				if l := len("refresh"); len(elem) >= l && elem[0:l] == "refresh" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "POST":
						r.name = APIRefreshPostOperation
						r.summary = "Refresh Token"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/api/refresh"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'v': // Prefix: "v"

				if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '1': // Prefix: "1/"

					if l := len("1/"); len(elem) >= l && elem[0:l] == "1/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "components"

						if l := len("components"); len(elem) >= l && elem[0:l] == "components" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = APIV1ComponentsGetOperation
								r.summary = ""
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v1/components"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = APIV1ComponentsPostOperation
								r.summary = ""
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v1/components"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = APIV1ComponentsPutOperation
								r.summary = ""
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v1/components"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'i': // Prefix: "incidents"

						if l := len("incidents"); len(elem) >= l && elem[0:l] == "incidents" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = APIV1IncidentsGetOperation
								r.summary = ""
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v1/incidents"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/updates"

							if l := len("/updates"); len(elem) >= l && elem[0:l] == "/updates" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = APIV1IncidentsUpdatesPostOperation
									r.summary = ""
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v1/incidents/updates"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 't': // Prefix: "token"

						if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = APIV1TokenPostOperation
								r.summary = "Get authorization token for v2"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v1/token"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case '4': // Prefix: "4/"

					if l := len("4/"); len(elem) >= l && elem[0:l] == "4/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'b': // Prefix: "bulkgroup"

						if l := len("bulkgroup"); len(elem) >= l && elem[0:l] == "bulkgroup" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "action"

							if l := len("action"); len(elem) >= l && elem[0:l] == "action" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = APIV4BulkgroupactionDeleteOperation
									r.summary = "Remove From Many Groups"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/bulkgroupaction"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = APIV4BulkgroupactionPostOperation
									r.summary = "Add To Many Groups"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/bulkgroupaction"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = APIV4BulkgroupsDeleteOperation
									r.summary = "Bulk Delete Groups"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/bulkgroups"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = APIV4BulkgroupsPostOperation
									r.summary = "Bulk Create Groups"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/bulkgroups"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'c': // Prefix: "co"

						if l := len("co"); len(elem) >= l && elem[0:l] == "co" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'm': // Prefix: "mponent"

							if l := len("mponent"); len(elem) >= l && elem[0:l] == "mponent" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = APIV4ComponentDeleteOperation
									r.summary = "Delete Component"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/component"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = APIV4ComponentPostOperation
									r.summary = "Create Component"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/component"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = APIV4ComponentPutOperation
									r.summary = "Update Component"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/component"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'm': // Prefix: "move"
									origElem := elem
									if l := len("move"); len(elem) >= l && elem[0:l] == "move" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = APIV4ComponentMovePostOperation
											r.summary = "Move Component"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/api/v4/component/move"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

									elem = origElem
								case 's': // Prefix: "setstatus"
									origElem := elem
									if l := len("setstatus"); len(elem) >= l && elem[0:l] == "setstatus" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = APIV4ComponentSetstatusPostOperation
											r.summary = "Set Component Status"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/api/v4/component/setstatus"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[0] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = APIV4ComponentIDGetOperation
										r.summary = "Get Component"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/component/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'h': // Prefix: "history"

										if l := len("history"); len(elem) >= l && elem[0:l] == "history" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = APIV4ComponentIDHistoryGetOperation
												r.summary = "Get Component History"
												r.operationID = ""
												r.operationGroup = ""
												r.pathPattern = "/api/v4/component/{id}/history"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

									case 'u': // Prefix: "uptime"

										if l := len("uptime"); len(elem) >= l && elem[0:l] == "uptime" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = APIV4ComponentIDUptimeGetOperation
												r.summary = "Get Component Uptime"
												r.operationID = ""
												r.operationGroup = ""
												r.pathPattern = "/api/v4/component/{id}/uptime"
												r.args = args
												r.count = 1
												return r, true
											default:
												return
											}
										}

									}

								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = APIV4ComponentsGetOperation
										r.summary = "Get All Components"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/components"
										r.args = args
										r.count = 0
										return r, true
									case "POST":
										r.name = APIV4ComponentsPostOperation
										r.summary = "Search Components"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/components"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'h': // Prefix: "history"

										if l := len("history"); len(elem) >= l && elem[0:l] == "history" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = APIV4ComponentsHistoryGetOperation
												r.summary = "Get Components History"
												r.operationID = ""
												r.operationGroup = ""
												r.pathPattern = "/api/v4/components/history"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'g': // Prefix: "group/"

												if l := len("group/"); len(elem) >= l && elem[0:l] == "group/" {
													elem = elem[l:]
												} else {
													break
												}

												// Param: "id"
												// Leaf parameter, slashes are prohibited
												idx := strings.IndexByte(elem, '/')
												if idx >= 0 {
													break
												}
												args[0] = elem
												elem = ""

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "GET":
														r.name = APIV4ComponentsHistoryGroupIDGetOperation
														r.summary = "Get Component History for a group"
														r.operationID = ""
														r.operationGroup = ""
														r.pathPattern = "/api/v4/components/history/group/{id}"
														r.args = args
														r.count = 1
														return r, true
													default:
														return
													}
												}

											case 'i': // Prefix: "incident/"

												if l := len("incident/"); len(elem) >= l && elem[0:l] == "incident/" {
													elem = elem[l:]
												} else {
													break
												}

												// Param: "id"
												// Leaf parameter, slashes are prohibited
												idx := strings.IndexByte(elem, '/')
												if idx >= 0 {
													break
												}
												args[0] = elem
												elem = ""

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "GET":
														r.name = APIV4ComponentsHistoryIncidentIDGetOperation
														r.summary = "Get Component History for an incident"
														r.operationID = ""
														r.operationGroup = ""
														r.pathPattern = "/api/v4/components/history/incident/{id}"
														r.args = args
														r.count = 1
														return r, true
													default:
														return
													}
												}

											}

										}

									case 'u': // Prefix: "uptime"

										if l := len("uptime"); len(elem) >= l && elem[0:l] == "uptime" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = APIV4ComponentsUptimeGetOperation
												r.summary = "Get All Components Uptime"
												r.operationID = ""
												r.operationGroup = ""
												r.pathPattern = "/api/v4/components/uptime"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}

									}

								}

							}

						case 'n': // Prefix: "ntenttemplate"

							if l := len("ntenttemplate"); len(elem) >= l && elem[0:l] == "ntenttemplate" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = APIV4ContenttemplateGetOperation
									r.summary = "Get All Content Templates"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/contenttemplate"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = APIV4ContenttemplatePostOperation
									r.summary = "Create Content Template"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/contenttemplate"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = APIV4ContenttemplatePutOperation
									r.summary = "Update Content Template"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/contenttemplate"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = APIV4ContenttemplateIDDeleteOperation
										r.summary = "Delete Content Template"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/contenttemplate/{id}"
										r.args = args
										r.count = 1
										return r, true
									case "GET":
										r.name = APIV4ContenttemplateIDGetOperation
										r.summary = "Get Content Template"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/contenttemplate/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'g': // Prefix: "group"

						if l := len("group"); len(elem) >= l && elem[0:l] == "group" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								r.name = APIV4GroupPostOperation
								r.summary = "Create Group"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/group"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = APIV4GroupPutOperation
								r.summary = "Update Group"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/group"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = APIV4GroupIDDeleteOperation
									r.summary = "Delete Group"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/group/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = APIV4GroupIDGetOperation
									r.summary = "Get Group"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/group/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'a': // Prefix: "action"

							if l := len("action"); len(elem) >= l && elem[0:l] == "action" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = APIV4GroupactionDeleteOperation
									r.summary = "Remove from Group"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupaction"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = APIV4GroupactionPostOperation
									r.summary = "Add to Group"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupaction"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'c': // Prefix: "components/"

							if l := len("components/"); len(elem) >= l && elem[0:l] == "components/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = APIV4GroupcomponentsIDGetOperation
									r.summary = "Get Group Components"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupcomponents/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = APIV4GroupcomponentsIDPutOperation
									r.summary = "Put Group Components"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupcomponents/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'i': // Prefix: "incidents/"

							if l := len("incidents/"); len(elem) >= l && elem[0:l] == "incidents/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = APIV4GroupincidentsIDGetOperation
									r.summary = "Get Group Incidents"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupincidents/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = APIV4GroupincidentsIDPutOperation
									r.summary = "Put Group Incidents"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groupincidents/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = APIV4GroupsPostOperation
									r.summary = "Search Groups"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/groups"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case 'u': // Prefix: "ubscriptions/"

								if l := len("ubscriptions/"); len(elem) >= l && elem[0:l] == "ubscriptions/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = APIV4GroupsubscriptionsIDGetOperation
										r.summary = "Get Group Subscriptions"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/groupsubscriptions/{id}"
										r.args = args
										r.count = 1
										return r, true
									case "PUT":
										r.name = APIV4GroupsubscriptionsIDPutOperation
										r.summary = "Put Group Subscriptions"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/groupsubscriptions/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'i': // Prefix: "i"

						if l := len("i"); len(elem) >= l && elem[0:l] == "i" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'm': // Prefix: "mage/upload"

							if l := len("mage/upload"); len(elem) >= l && elem[0:l] == "mage/upload" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = PostApiv4imageuploadOperation
									r.summary = ""
									r.operationID = "post_apiv4imageupload"
									r.operationGroup = ""
									r.pathPattern = "/api/v4/image/upload"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'n': // Prefix: "ncident"

							if l := len("ncident"); len(elem) >= l && elem[0:l] == "ncident" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = APIV4IncidentPostOperation
									r.summary = "Create Incident"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/incident"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = APIV4IncidentPutOperation
									r.summary = "Update Incident"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/incident"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'q': // Prefix: "queue"
									origElem := elem
									if l := len("queue"); len(elem) >= l && elem[0:l] == "queue" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = APIV4IncidentQueuePostOperation
											r.summary = "Create Incident"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/api/v4/incident/queue"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = APIV4IncidentIDDeleteOperation
										r.summary = "Delete Incident"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/incident/{id}"
										r.args = args
										r.count = 1
										return r, true
									case "GET":
										r.name = APIV4IncidentIDGetOperation
										r.summary = "Get Incident"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/incident/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = APIV4IncidentsPostOperation
										r.summary = "Search Incidents"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/incidents"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'u': // Prefix: "update/"

								if l := len("update/"); len(elem) >= l && elem[0:l] == "update/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = APIV4IncidentupdateIDDeleteOperation
										r.summary = "Delete Incident Update"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/incidentupdate/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'm': // Prefix: "metric"

						if l := len("metric"); len(elem) >= l && elem[0:l] == "metric" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = APIV4MetricDeleteOperation
								r.summary = "Delete Metric Data"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/metric"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = APIV4MetricPostOperation
								r.summary = "Create Metric Data"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/metric"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = APIV4MetricsPostOperation
									r.summary = "Search Metrics"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/metrics"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'p': // Prefix: "p"

						if l := len("p"); len(elem) >= l && elem[0:l] == "p" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "age"

							if l := len("age"); len(elem) >= l && elem[0:l] == "age" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = APIV4PagePostOperation
									r.summary = "Create Page"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/page"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = APIV4PagePutOperation
									r.summary = "Update Page"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/page"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 's': // Prefix: "status"
									origElem := elem
									if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = APIV4PageStatusGetOperation
											r.summary = "Get Page Status"
											r.operationID = ""
											r.operationGroup = ""
											r.pathPattern = "/api/v4/page/status"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = APIV4PageIDGetOperation
										r.summary = "Get Page"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/page/{id}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = APIV4PagesPostOperation
										r.summary = "Search Pages"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/pages"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						case 'u': // Prefix: "ublicstatuspages"

							if l := len("ublicstatuspages"); len(elem) >= l && elem[0:l] == "ublicstatuspages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = APIV4PublicstatuspagesGetOperation
									r.summary = "Search public pages as an asynchronous operation."
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/publicstatuspages"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 's': // Prefix: "subscriber"

						if l := len("subscriber"); len(elem) >= l && elem[0:l] == "subscriber" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								r.name = APIV4SubscriberPostOperation
								r.summary = "Create Subscriber"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/subscriber"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = APIV4SubscriberPutOperation
								r.summary = "Update Subscriber"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/subscriber"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = APIV4SubscriberIDDeleteOperation
									r.summary = "Delete Subscriber"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/subscriber/{id}"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = APIV4SubscriberIDGetOperation
									r.summary = "Get Subscriber"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/subscriber/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/reinvite"

								if l := len("/reinvite"); len(elem) >= l && elem[0:l] == "/reinvite" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = APIV4SubscriberIDReinvitePostOperation
										r.summary = "Re-Invite Subscriber"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/subscriber/{id}/reinvite"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = APIV4SubscribersPostOperation
									r.summary = "Create Subscribers"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/subscribers"
									r.args = args
									r.count = 0
									return r, true
								case "PUT":
									r.name = APIV4SubscribersPutOperation
									r.summary = "Update Subscribers"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/subscribers"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/search"

								if l := len("/search"); len(elem) >= l && elem[0:l] == "/search" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = APIV4SubscribersSearchPostOperation
										r.summary = "Search Subscribers"
										r.operationID = ""
										r.operationGroup = ""
										r.pathPattern = "/api/v4/subscribers/search"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'u': // Prefix: "user"

						if l := len("user"); len(elem) >= l && elem[0:l] == "user" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = APIV4UserDeleteOperation
								r.summary = "Delete User"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/user"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = APIV4UserPostOperation
								r.summary = "Create User"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/user"
								r.args = args
								r.count = 0
								return r, true
							case "PUT":
								r.name = APIV4UserPutOperation
								r.summary = "Update User"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/api/v4/user"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = APIV4UserIDGetOperation
									r.summary = "Get User"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/user/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = APIV4UsersPostOperation
									r.summary = "Search Users"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/api/v4/users"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
