// Code generated by ogen, DO NOT EDIT.
package statuscast

type API4meAppPostRes interface {
	aPI4meAppPostRes()
}

type API4meConfigPostReq interface {
	aPI4meConfigPostReq()
}

type APIAuthenticatePostRes interface {
	aPIAuthenticatePostRes()
}

type APIV1ComponentsGetRes interface {
	aPIV1ComponentsGetRes()
}

type APIV1ComponentsPostRes interface {
	aPIV1ComponentsPostRes()
}

type APIV1ComponentsPutRes interface {
	aPIV1ComponentsPutRes()
}

type APIV1IncidentsGetRes interface {
	aPIV1IncidentsGetRes()
}

type APIV1IncidentsUpdatesPostRes interface {
	aPIV1IncidentsUpdatesPostRes()
}

type APIV1TokenPostRes interface {
	aPIV1TokenPostRes()
}

type APIV4BulkgroupactionDeleteRes interface {
	aPIV4BulkgroupactionDeleteRes()
}

type APIV4BulkgroupactionPostRes interface {
	aPIV4BulkgroupactionPostRes()
}

type APIV4BulkgroupsDeleteReq interface {
	aPIV4BulkgroupsDeleteReq()
}

type APIV4BulkgroupsDeleteRes interface {
	aPIV4BulkgroupsDeleteRes()
}

type APIV4BulkgroupsPostRes interface {
	aPIV4BulkgroupsPostRes()
}

type APIV4ComponentDeleteRes interface {
	aPIV4ComponentDeleteRes()
}

type APIV4ComponentIDGetRes interface {
	aPIV4ComponentIDGetRes()
}

type APIV4ComponentIDHistoryGetRes interface {
	aPIV4ComponentIDHistoryGetRes()
}

type APIV4ComponentIDUptimeGetRes interface {
	aPIV4ComponentIDUptimeGetRes()
}

type APIV4ComponentMovePostRes interface {
	aPIV4ComponentMovePostRes()
}

type APIV4ComponentPostRes interface {
	aPIV4ComponentPostRes()
}

type APIV4ComponentPutRes interface {
	aPIV4ComponentPutRes()
}

type APIV4ComponentSetstatusPostRes interface {
	aPIV4ComponentSetstatusPostRes()
}

type APIV4ComponentsGetRes interface {
	aPIV4ComponentsGetRes()
}

type APIV4ComponentsHistoryGetRes interface {
	aPIV4ComponentsHistoryGetRes()
}

type APIV4ComponentsHistoryGroupIDGetRes interface {
	aPIV4ComponentsHistoryGroupIDGetRes()
}

type APIV4ComponentsHistoryIncidentIDGetRes interface {
	aPIV4ComponentsHistoryIncidentIDGetRes()
}

type APIV4ComponentsPostRes interface {
	aPIV4ComponentsPostRes()
}

type APIV4ComponentsUptimeGetRes interface {
	aPIV4ComponentsUptimeGetRes()
}

type APIV4ContenttemplateGetRes interface {
	aPIV4ContenttemplateGetRes()
}

type APIV4ContenttemplateIDDeleteRes interface {
	aPIV4ContenttemplateIDDeleteRes()
}

type APIV4ContenttemplateIDGetRes interface {
	aPIV4ContenttemplateIDGetRes()
}

type APIV4ContenttemplatePostRes interface {
	aPIV4ContenttemplatePostRes()
}

type APIV4ContenttemplatePutRes interface {
	aPIV4ContenttemplatePutRes()
}

type APIV4GroupIDDeleteRes interface {
	aPIV4GroupIDDeleteRes()
}

type APIV4GroupIDGetRes interface {
	aPIV4GroupIDGetRes()
}

type APIV4GroupPostRes interface {
	aPIV4GroupPostRes()
}

type APIV4GroupPutRes interface {
	aPIV4GroupPutRes()
}

type APIV4GroupactionDeleteRes interface {
	aPIV4GroupactionDeleteRes()
}

type APIV4GroupactionPostRes interface {
	aPIV4GroupactionPostRes()
}

type APIV4GroupcomponentsIDGetRes interface {
	aPIV4GroupcomponentsIDGetRes()
}

type APIV4GroupcomponentsIDPutReq interface {
	aPIV4GroupcomponentsIDPutReq()
}

type APIV4GroupcomponentsIDPutRes interface {
	aPIV4GroupcomponentsIDPutRes()
}

type APIV4GroupincidentsIDGetRes interface {
	aPIV4GroupincidentsIDGetRes()
}

type APIV4GroupincidentsIDPutReq interface {
	aPIV4GroupincidentsIDPutReq()
}

type APIV4GroupincidentsIDPutRes interface {
	aPIV4GroupincidentsIDPutRes()
}

type APIV4GroupsPostRes interface {
	aPIV4GroupsPostRes()
}

type APIV4GroupsubscriptionsIDGetRes interface {
	aPIV4GroupsubscriptionsIDGetRes()
}

type APIV4GroupsubscriptionsIDPutReq interface {
	aPIV4GroupsubscriptionsIDPutReq()
}

type APIV4GroupsubscriptionsIDPutRes interface {
	aPIV4GroupsubscriptionsIDPutRes()
}

type APIV4IncidentIDDeleteRes interface {
	aPIV4IncidentIDDeleteRes()
}

type APIV4IncidentIDGetRes interface {
	aPIV4IncidentIDGetRes()
}

type APIV4IncidentPostRes interface {
	aPIV4IncidentPostRes()
}

type APIV4IncidentPutRes interface {
	aPIV4IncidentPutRes()
}

type APIV4IncidentQueuePostRes interface {
	aPIV4IncidentQueuePostRes()
}

type APIV4IncidentsPostRes interface {
	aPIV4IncidentsPostRes()
}

type APIV4IncidentupdateIDDeleteRes interface {
	aPIV4IncidentupdateIDDeleteRes()
}

type APIV4MetricDeleteRes interface {
	aPIV4MetricDeleteRes()
}

type APIV4MetricPostRes interface {
	aPIV4MetricPostRes()
}

type APIV4MetricsPostRes interface {
	aPIV4MetricsPostRes()
}

type APIV4PageIDGetRes interface {
	aPIV4PageIDGetRes()
}

type APIV4PagePostRes interface {
	aPIV4PagePostRes()
}

type APIV4PagePutRes interface {
	aPIV4PagePutRes()
}

type APIV4PageStatusGetRes interface {
	aPIV4PageStatusGetRes()
}

type APIV4PagesPostRes interface {
	aPIV4PagesPostRes()
}

type APIV4PublicstatuspagesGetRes interface {
	aPIV4PublicstatuspagesGetRes()
}

type APIV4SubscriberIDDeleteRes interface {
	aPIV4SubscriberIDDeleteRes()
}

type APIV4SubscriberIDGetRes interface {
	aPIV4SubscriberIDGetRes()
}

type APIV4SubscriberIDReinvitePostRes interface {
	aPIV4SubscriberIDReinvitePostRes()
}

type APIV4SubscriberPostRes interface {
	aPIV4SubscriberPostRes()
}

type APIV4SubscriberPutRes interface {
	aPIV4SubscriberPutRes()
}

type APIV4SubscribersPostRes interface {
	aPIV4SubscribersPostRes()
}

type APIV4SubscribersPutRes interface {
	aPIV4SubscribersPutRes()
}

type APIV4SubscribersSearchPostRes interface {
	aPIV4SubscribersSearchPostRes()
}

type APIV4UserDeleteRes interface {
	aPIV4UserDeleteRes()
}

type APIV4UserIDGetRes interface {
	aPIV4UserIDGetRes()
}

type APIV4UserPostRes interface {
	aPIV4UserPostRes()
}

type APIV4UserPutRes interface {
	aPIV4UserPutRes()
}

type APIV4UsersPostRes interface {
	aPIV4UsersPostRes()
}

type PostApiv4imageuploadRes interface {
	postApiv4imageuploadRes()
}
