// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIV1ComponentsPutParams is parameters of PUT /api/v1/components operation.
type APIV1ComponentsPutParams struct {
	ID OptInt32 `json:",omitempty,omitzero"`
}

func unpackAPIV1ComponentsPutParams(packed middleware.Parameters) (params APIV1ComponentsPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ID = v.(OptInt32)
		}
	}
	return params
}

func decodeAPIV1ComponentsPutParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1ComponentsPutParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIDVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ID.SetTo(paramsDotIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV1IncidentsGetParams is parameters of GET /api/v1/incidents operation.
type APIV1IncidentsGetParams struct {
	ID OptInt32 `json:",omitempty,omitzero"`
}

func unpackAPIV1IncidentsGetParams(packed middleware.Parameters) (params APIV1IncidentsGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ID = v.(OptInt32)
		}
	}
	return params
}

func decodeAPIV1IncidentsGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1IncidentsGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIDVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ID.SetTo(paramsDotIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentDeleteParams is parameters of DELETE /api/v4/component operation.
type APIV4ComponentDeleteParams struct {
	// The identifier.
	ID int32
	// The reassign incidents to identifier.
	ReassignIncidentsToId OptInt32 `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentDeleteParams(packed middleware.Parameters) (params APIV4ComponentDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		params.ID = packed[key].(int32)
	}
	{
		key := middleware.ParameterKey{
			Name: "reassignIncidentsToId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ReassignIncidentsToId = v.(OptInt32)
		}
	}
	return params
}

func decodeAPIV4ComponentDeleteParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV4ComponentDeleteParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: reassignIncidentsToId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "reassignIncidentsToId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotReassignIncidentsToIdVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotReassignIncidentsToIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ReassignIncidentsToId.SetTo(paramsDotReassignIncidentsToIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "reassignIncidentsToId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentIDGetParams is parameters of GET /api/v4/component/{id} operation.
type APIV4ComponentIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4ComponentIDGetParams(packed middleware.Parameters) (params APIV4ComponentIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4ComponentIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ComponentIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentIDHistoryGetParams is parameters of GET /api/v4/component/{id}/history operation.
type APIV4ComponentIDHistoryGetParams struct {
	// The identifier.
	ID int32
	// The range.
	Range OptAPIV4ComponentIDHistoryGetRange `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentIDHistoryGetParams(packed middleware.Parameters) (params APIV4ComponentIDHistoryGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	{
		key := middleware.ParameterKey{
			Name: "range",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Range = v.(OptAPIV4ComponentIDHistoryGetRange)
		}
	}
	return params
}

func decodeAPIV4ComponentIDHistoryGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ComponentIDHistoryGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: range.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "range",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRangeVal APIV4ComponentIDHistoryGetRange
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRangeVal = APIV4ComponentIDHistoryGetRange(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Range.SetTo(paramsDotRangeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Range.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "range",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentIDUptimeGetParams is parameters of GET /api/v4/component/{id}/uptime operation.
type APIV4ComponentIDUptimeGetParams struct {
	// The identifier.
	ID int32
	// The group identifier.
	GroupId OptInt32 `json:",omitempty,omitzero"`
	// The range.
	Range OptAPIV4ComponentIDUptimeGetRange `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentIDUptimeGetParams(packed middleware.Parameters) (params APIV4ComponentIDUptimeGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	{
		key := middleware.ParameterKey{
			Name: "groupId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.GroupId = v.(OptInt32)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "range",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Range = v.(OptAPIV4ComponentIDUptimeGetRange)
		}
	}
	return params
}

func decodeAPIV4ComponentIDUptimeGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ComponentIDUptimeGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: groupId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "groupId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotGroupIdVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotGroupIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.GroupId.SetTo(paramsDotGroupIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: range.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "range",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRangeVal APIV4ComponentIDUptimeGetRange
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRangeVal = APIV4ComponentIDUptimeGetRange(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Range.SetTo(paramsDotRangeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Range.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "range",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentsHistoryGetParams is parameters of GET /api/v4/components/history operation.
type APIV4ComponentsHistoryGetParams struct {
	// The range.
	Range OptAPIV4ComponentsHistoryGetRange `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentsHistoryGetParams(packed middleware.Parameters) (params APIV4ComponentsHistoryGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "range",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Range = v.(OptAPIV4ComponentsHistoryGetRange)
		}
	}
	return params
}

func decodeAPIV4ComponentsHistoryGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV4ComponentsHistoryGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: range.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "range",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRangeVal APIV4ComponentsHistoryGetRange
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRangeVal = APIV4ComponentsHistoryGetRange(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Range.SetTo(paramsDotRangeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Range.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "range",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentsHistoryGroupIDGetParams is parameters of GET /api/v4/components/history/group/{id} operation.
type APIV4ComponentsHistoryGroupIDGetParams struct {
	// The group identifier.
	ID int32
	// The range.
	Range OptAPIV4ComponentsHistoryGroupIDGetRange `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentsHistoryGroupIDGetParams(packed middleware.Parameters) (params APIV4ComponentsHistoryGroupIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	{
		key := middleware.ParameterKey{
			Name: "range",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Range = v.(OptAPIV4ComponentsHistoryGroupIDGetRange)
		}
	}
	return params
}

func decodeAPIV4ComponentsHistoryGroupIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ComponentsHistoryGroupIDGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: range.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "range",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRangeVal APIV4ComponentsHistoryGroupIDGetRange
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRangeVal = APIV4ComponentsHistoryGroupIDGetRange(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Range.SetTo(paramsDotRangeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Range.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "range",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentsHistoryIncidentIDGetParams is parameters of GET /api/v4/components/history/incident/{id} operation.
type APIV4ComponentsHistoryIncidentIDGetParams struct {
	// The incident identifier.
	ID int32
}

func unpackAPIV4ComponentsHistoryIncidentIDGetParams(packed middleware.Parameters) (params APIV4ComponentsHistoryIncidentIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4ComponentsHistoryIncidentIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ComponentsHistoryIncidentIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ComponentsUptimeGetParams is parameters of GET /api/v4/components/uptime operation.
type APIV4ComponentsUptimeGetParams struct {
	// The group identifier.
	GroupId OptInt32 `json:",omitempty,omitzero"`
	// The ids.
	Ids OptString `json:",omitempty,omitzero"`
	// The range.
	Range OptAPIV4ComponentsUptimeGetRange `json:",omitempty,omitzero"`
}

func unpackAPIV4ComponentsUptimeGetParams(packed middleware.Parameters) (params APIV4ComponentsUptimeGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.GroupId = v.(OptInt32)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "ids",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Ids = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "range",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Range = v.(OptAPIV4ComponentsUptimeGetRange)
		}
	}
	return params
}

func decodeAPIV4ComponentsUptimeGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV4ComponentsUptimeGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: groupId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "groupId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotGroupIdVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotGroupIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.GroupId.SetTo(paramsDotGroupIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: ids.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "ids",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIdsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIdsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Ids.SetTo(paramsDotIdsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ids",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: range.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "range",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRangeVal APIV4ComponentsUptimeGetRange
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRangeVal = APIV4ComponentsUptimeGetRange(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Range.SetTo(paramsDotRangeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Range.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "range",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ContenttemplateIDDeleteParams is parameters of DELETE /api/v4/contenttemplate/{id} operation.
type APIV4ContenttemplateIDDeleteParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4ContenttemplateIDDeleteParams(packed middleware.Parameters) (params APIV4ContenttemplateIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4ContenttemplateIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ContenttemplateIDDeleteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4ContenttemplateIDGetParams is parameters of GET /api/v4/contenttemplate/{id} operation.
type APIV4ContenttemplateIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4ContenttemplateIDGetParams(packed middleware.Parameters) (params APIV4ContenttemplateIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4ContenttemplateIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4ContenttemplateIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupIDDeleteParams is parameters of DELETE /api/v4/group/{id} operation.
type APIV4GroupIDDeleteParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupIDDeleteParams(packed middleware.Parameters) (params APIV4GroupIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupIDDeleteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupIDGetParams is parameters of GET /api/v4/group/{id} operation.
type APIV4GroupIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupIDGetParams(packed middleware.Parameters) (params APIV4GroupIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupcomponentsIDGetParams is parameters of GET /api/v4/groupcomponents/{id} operation.
type APIV4GroupcomponentsIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupcomponentsIDGetParams(packed middleware.Parameters) (params APIV4GroupcomponentsIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupcomponentsIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupcomponentsIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupcomponentsIDPutParams is parameters of PUT /api/v4/groupcomponents/{id} operation.
type APIV4GroupcomponentsIDPutParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupcomponentsIDPutParams(packed middleware.Parameters) (params APIV4GroupcomponentsIDPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupcomponentsIDPutParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupcomponentsIDPutParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupincidentsIDGetParams is parameters of GET /api/v4/groupincidents/{id} operation.
type APIV4GroupincidentsIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupincidentsIDGetParams(packed middleware.Parameters) (params APIV4GroupincidentsIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupincidentsIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupincidentsIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupincidentsIDPutParams is parameters of PUT /api/v4/groupincidents/{id} operation.
type APIV4GroupincidentsIDPutParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupincidentsIDPutParams(packed middleware.Parameters) (params APIV4GroupincidentsIDPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupincidentsIDPutParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupincidentsIDPutParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupsubscriptionsIDGetParams is parameters of GET /api/v4/groupsubscriptions/{id} operation.
type APIV4GroupsubscriptionsIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupsubscriptionsIDGetParams(packed middleware.Parameters) (params APIV4GroupsubscriptionsIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupsubscriptionsIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupsubscriptionsIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4GroupsubscriptionsIDPutParams is parameters of PUT /api/v4/groupsubscriptions/{id} operation.
type APIV4GroupsubscriptionsIDPutParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4GroupsubscriptionsIDPutParams(packed middleware.Parameters) (params APIV4GroupsubscriptionsIDPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4GroupsubscriptionsIDPutParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4GroupsubscriptionsIDPutParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4IncidentIDDeleteParams is parameters of DELETE /api/v4/incident/{id} operation.
type APIV4IncidentIDDeleteParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4IncidentIDDeleteParams(packed middleware.Parameters) (params APIV4IncidentIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4IncidentIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4IncidentIDDeleteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4IncidentIDGetParams is parameters of GET /api/v4/incident/{id} operation.
type APIV4IncidentIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4IncidentIDGetParams(packed middleware.Parameters) (params APIV4IncidentIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4IncidentIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4IncidentIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4IncidentupdateIDDeleteParams is parameters of DELETE /api/v4/incidentupdate/{id} operation.
type APIV4IncidentupdateIDDeleteParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4IncidentupdateIDDeleteParams(packed middleware.Parameters) (params APIV4IncidentupdateIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4IncidentupdateIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4IncidentupdateIDDeleteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4PageIDGetParams is parameters of GET /api/v4/page/{id} operation.
type APIV4PageIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4PageIDGetParams(packed middleware.Parameters) (params APIV4PageIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4PageIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4PageIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4PublicstatuspagesGetParams is parameters of GET /api/v4/publicstatuspages operation.
type APIV4PublicstatuspagesGetParams struct {
	// The search.
	Search OptString `json:",omitempty,omitzero"`
	// The page.
	Page OptInt32 `json:",omitempty,omitzero"`
	// The pagesize.
	Pagesize OptInt32 `json:",omitempty,omitzero"`
}

func unpackAPIV4PublicstatuspagesGetParams(packed middleware.Parameters) (params APIV4PublicstatuspagesGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "search",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Search = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Page = v.(OptInt32)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "pagesize",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Pagesize = v.(OptInt32)
		}
	}
	return params
}

func decodeAPIV4PublicstatuspagesGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV4PublicstatuspagesGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: search.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "search",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSearchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSearchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Search.SetTo(paramsDotSearchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "search",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: page.
	{
		val := int32(1)
		params.Page.SetTo(val)
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPageVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotPageVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Page.SetTo(paramsDotPageVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: pagesize.
	{
		val := int32(10)
		params.Pagesize.SetTo(val)
	}
	// Decode query: pagesize.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "pagesize",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPagesizeVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotPagesizeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Pagesize.SetTo(paramsDotPagesizeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pagesize",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4SubscriberIDDeleteParams is parameters of DELETE /api/v4/subscriber/{id} operation.
type APIV4SubscriberIDDeleteParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4SubscriberIDDeleteParams(packed middleware.Parameters) (params APIV4SubscriberIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4SubscriberIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4SubscriberIDDeleteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4SubscriberIDGetParams is parameters of GET /api/v4/subscriber/{id} operation.
type APIV4SubscriberIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4SubscriberIDGetParams(packed middleware.Parameters) (params APIV4SubscriberIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4SubscriberIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4SubscriberIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4SubscriberIDReinvitePostParams is parameters of POST /api/v4/subscriber/{id}/reinvite operation.
type APIV4SubscriberIDReinvitePostParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4SubscriberIDReinvitePostParams(packed middleware.Parameters) (params APIV4SubscriberIDReinvitePostParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4SubscriberIDReinvitePostParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4SubscriberIDReinvitePostParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4UserDeleteParams is parameters of DELETE /api/v4/user operation.
type APIV4UserDeleteParams struct {
	// The identifier.
	ID uuid.UUID
	// The reassign identifier.
	ReassignId uuid.UUID
}

func unpackAPIV4UserDeleteParams(packed middleware.Parameters) (params APIV4UserDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "reassignId",
			In:   "query",
		}
		params.ReassignId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIV4UserDeleteParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV4UserDeleteParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: reassignId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "reassignId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ReassignId = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "reassignId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIV4UserIDGetParams is parameters of GET /api/v4/user/{id} operation.
type APIV4UserIDGetParams struct {
	// The identifier.
	ID int32
}

func unpackAPIV4UserIDGetParams(packed middleware.Parameters) (params APIV4UserIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int32)
	}
	return params
}

func decodeAPIV4UserIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIV4UserIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
