// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func encodeAPI4meAppPostResponse(response API4meAppPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *API4meAppPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *API4meAppPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *API4meAppPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *API4meAppPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPI4meConfigPostResponse(response *API4meConfigPostOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeAPIAuthenticatePostResponse(response APIAuthenticatePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIAuthenticatePostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIAuthenticatePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIAuthenticatePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIAuthenticatePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIRefreshPostResponse(response *APIRefreshPostOK, w http.ResponseWriter, span trace.Span) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	e := new(jx.Encoder)
	response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeAPIV1ComponentsGetResponse(response APIV1ComponentsGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ComponentsGetOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV1ComponentsGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ComponentsGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ComponentsGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ComponentsPostResponse(response APIV1ComponentsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ComponentsPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV1ComponentsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ComponentsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ComponentsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1ComponentsPutResponse(response APIV1ComponentsPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1ComponentsPutOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV1ComponentsPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1ComponentsPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1ComponentsPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1IncidentsGetResponse(response APIV1IncidentsGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1IncidentsGetOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV1IncidentsGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1IncidentsGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1IncidentsGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1IncidentsUpdatesPostResponse(response APIV1IncidentsUpdatesPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1IncidentsUpdatesPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1IncidentsUpdatesPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1IncidentsUpdatesPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1IncidentsUpdatesPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV1TokenPostResponse(response APIV1TokenPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV1TokenPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV1TokenPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV1TokenPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV1TokenPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4BulkgroupactionDeleteResponse(response APIV4BulkgroupactionDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4BulkgroupactionDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4BulkgroupactionDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4BulkgroupactionDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4BulkgroupactionDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4BulkgroupactionPostResponse(response APIV4BulkgroupactionPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4BulkgroupactionPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4BulkgroupactionPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4BulkgroupactionPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4BulkgroupactionPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4BulkgroupsDeleteResponse(response APIV4BulkgroupsDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4BulkgroupsDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4BulkgroupsDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4BulkgroupsDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4BulkgroupsDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4BulkgroupsPostResponse(response APIV4BulkgroupsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4BulkgroupsPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4BulkgroupsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4BulkgroupsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4BulkgroupsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentDeleteResponse(response APIV4ComponentDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4ComponentDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentIDGetResponse(response APIV4ComponentIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentIDHistoryGetResponse(response APIV4ComponentIDHistoryGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentIDHistoryGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentIDHistoryGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentIDHistoryGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentIDHistoryGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentIDUptimeGetResponse(response APIV4ComponentIDUptimeGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentIDUptimeGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentIDUptimeGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentIDUptimeGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentIDUptimeGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentMovePostResponse(response APIV4ComponentMovePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentMovePostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentMovePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentMovePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentMovePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentPostResponse(response APIV4ComponentPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentPutResponse(response APIV4ComponentPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentPutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentSetstatusPostResponse(response APIV4ComponentSetstatusPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentSetstatusPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4ComponentSetstatusPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentSetstatusPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentSetstatusPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsGetResponse(response APIV4ComponentsGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsHistoryGetResponse(response APIV4ComponentsHistoryGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsHistoryGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsHistoryGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsHistoryGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsHistoryGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsHistoryGroupIDGetResponse(response APIV4ComponentsHistoryGroupIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsHistoryGroupIDGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsHistoryGroupIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsHistoryGroupIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsHistoryGroupIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsHistoryIncidentIDGetResponse(response APIV4ComponentsHistoryIncidentIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsHistoryIncidentIDGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsHistoryIncidentIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsHistoryIncidentIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsHistoryIncidentIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsPostResponse(response APIV4ComponentsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ComponentsUptimeGetResponse(response APIV4ComponentsUptimeGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ComponentsUptimeGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ComponentsUptimeGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ComponentsUptimeGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ComponentsUptimeGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ContenttemplateGetResponse(response APIV4ContenttemplateGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ContenttemplateGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ContenttemplateGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ContenttemplateGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ContenttemplateGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ContenttemplateIDDeleteResponse(response APIV4ContenttemplateIDDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ContenttemplateIDDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4ContenttemplateIDDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ContenttemplateIDDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ContenttemplateIDDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ContenttemplateIDGetResponse(response APIV4ContenttemplateIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ContenttemplateIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ContenttemplateIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ContenttemplateIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ContenttemplateIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ContenttemplatePostResponse(response APIV4ContenttemplatePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ContenttemplatePostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ContenttemplatePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ContenttemplatePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ContenttemplatePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4ContenttemplatePutResponse(response APIV4ContenttemplatePutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4ContenttemplatePutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4ContenttemplatePutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4ContenttemplatePutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4ContenttemplatePutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupIDDeleteResponse(response APIV4GroupIDDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupIDDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupIDDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupIDDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupIDDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupIDGetResponse(response APIV4GroupIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupPostResponse(response APIV4GroupPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupPutResponse(response APIV4GroupPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupPutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupactionDeleteResponse(response APIV4GroupactionDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupactionDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupactionDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupactionDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupactionDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupactionPostResponse(response APIV4GroupactionPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupactionPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupactionPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupactionPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupactionPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupcomponentsIDGetResponse(response APIV4GroupcomponentsIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupcomponentsIDGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupcomponentsIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupcomponentsIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupcomponentsIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupcomponentsIDPutResponse(response APIV4GroupcomponentsIDPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupcomponentsIDPutOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupcomponentsIDPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupcomponentsIDPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupcomponentsIDPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupincidentsIDGetResponse(response APIV4GroupincidentsIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupincidentsIDGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupincidentsIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupincidentsIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupincidentsIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupincidentsIDPutResponse(response APIV4GroupincidentsIDPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupincidentsIDPutOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupincidentsIDPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupincidentsIDPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupincidentsIDPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupsPostResponse(response APIV4GroupsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupsPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupsubscriptionsIDGetResponse(response APIV4GroupsubscriptionsIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupsubscriptionsIDGetOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4GroupsubscriptionsIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupsubscriptionsIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupsubscriptionsIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4GroupsubscriptionsIDPutResponse(response APIV4GroupsubscriptionsIDPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4GroupsubscriptionsIDPutOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4GroupsubscriptionsIDPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4GroupsubscriptionsIDPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4GroupsubscriptionsIDPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentIDDeleteResponse(response APIV4IncidentIDDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentIDDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4IncidentIDDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentIDDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentIDDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentIDGetResponse(response APIV4IncidentIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4IncidentIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentPostResponse(response APIV4IncidentPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4IncidentPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentPutResponse(response APIV4IncidentPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentPutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4IncidentPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentQueuePostResponse(response APIV4IncidentQueuePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentQueuePostOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4IncidentQueuePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentQueuePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentQueuePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentsPostResponse(response APIV4IncidentsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentsPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4IncidentsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4IncidentupdateIDDeleteResponse(response APIV4IncidentupdateIDDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4IncidentupdateIDDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4IncidentupdateIDDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4IncidentupdateIDDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4IncidentupdateIDDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4MetricDeleteResponse(response APIV4MetricDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4MetricDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4MetricDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4MetricDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4MetricDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4MetricPostResponse(response APIV4MetricPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4MetricPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4MetricPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4MetricPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4MetricPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4MetricsPostResponse(response APIV4MetricsPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4MetricsPostOKApplicationJSON:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4MetricsPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4MetricsPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4MetricsPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PageIDGetResponse(response APIV4PageIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PageIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PageIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PageIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PageIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PagePostResponse(response APIV4PagePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PagePostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PagePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PagePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PagePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PagePutResponse(response APIV4PagePutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PagePutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PagePutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PagePutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PagePutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PageStatusGetResponse(response APIV4PageStatusGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PageStatusGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PageStatusGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PageStatusGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PageStatusGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PagesPostResponse(response APIV4PagesPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PagesPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PagesPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PagesPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PagesPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4PublicstatuspagesGetResponse(response APIV4PublicstatuspagesGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4PublicstatuspagesGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4PublicstatuspagesGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4PublicstatuspagesGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4PublicstatuspagesGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscriberIDDeleteResponse(response APIV4SubscriberIDDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscriberIDDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4SubscriberIDDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscriberIDDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscriberIDDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscriberIDGetResponse(response APIV4SubscriberIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscriberIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4SubscriberIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscriberIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscriberIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscriberIDReinvitePostResponse(response APIV4SubscriberIDReinvitePostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscriberIDReinvitePostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4SubscriberIDReinvitePostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscriberIDReinvitePostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscriberIDReinvitePostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscriberPostResponse(response APIV4SubscriberPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscriberPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4SubscriberPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscriberPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscriberPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscriberPutResponse(response APIV4SubscriberPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscriberPutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4SubscriberPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscriberPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscriberPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscribersPostResponse(response APIV4SubscribersPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscribersPostOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4SubscribersPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscribersPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscribersPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscribersPutResponse(response APIV4SubscribersPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscribersPutOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4SubscribersPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscribersPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscribersPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4SubscribersSearchPostResponse(response APIV4SubscribersSearchPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4SubscribersSearchPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4SubscribersSearchPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4SubscribersSearchPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4SubscribersSearchPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4UserDeleteResponse(response APIV4UserDeleteRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4UserDeleteOK:
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		return nil

	case *APIV4UserDeleteUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4UserDeleteForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4UserDeleteMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4UserIDGetResponse(response APIV4UserIDGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4UserIDGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4UserIDGetUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4UserIDGetForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4UserIDGetMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4UserPostResponse(response APIV4UserPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4UserPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4UserPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4UserPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4UserPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4UserPutResponse(response APIV4UserPutRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4UserPutOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4UserPutUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4UserPutForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4UserPutMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeAPIV4UsersPostResponse(response APIV4UsersPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *APIV4UsersPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *APIV4UsersPostUnauthorized:
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		return nil

	case *APIV4UsersPostForbidden:
		w.WriteHeader(403)
		span.SetStatus(codes.Error, http.StatusText(403))

		return nil

	case *APIV4UsersPostMethodNotAllowed:
		w.WriteHeader(405)
		span.SetStatus(codes.Error, http.StatusText(405))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodePostApiv4imageuploadResponse(response PostApiv4imageuploadRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *PostApiv4imageuploadOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *PostApiv4imageuploadUnauthorized:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(401)
		span.SetStatus(codes.Error, http.StatusText(401))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *PostApiv4imageuploadUnprocessableEntity:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(422)
		span.SetStatus(codes.Error, http.StatusText(422))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
