// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearer handles Bearer security.
	// Put **_ONLY_** your JWT Bearer token on textbox below!.
	HandleBearer(ctx context.Context, operationName OperationName, t Bearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearer is a private map storing roles per operation.
var operationRolesBearer = map[string][]string{
	API4meAppPostOperation:                       []string{},
	APIAuthenticatePostOperation:                 []string{},
	APIV1ComponentsGetOperation:                  []string{},
	APIV1ComponentsPostOperation:                 []string{},
	APIV1ComponentsPutOperation:                  []string{},
	APIV1IncidentsGetOperation:                   []string{},
	APIV1IncidentsUpdatesPostOperation:           []string{},
	APIV1TokenPostOperation:                      []string{},
	APIV4BulkgroupactionDeleteOperation:          []string{},
	APIV4BulkgroupactionPostOperation:            []string{},
	APIV4BulkgroupsDeleteOperation:               []string{},
	APIV4BulkgroupsPostOperation:                 []string{},
	APIV4ComponentDeleteOperation:                []string{},
	APIV4ComponentIDGetOperation:                 []string{},
	APIV4ComponentIDHistoryGetOperation:          []string{},
	APIV4ComponentIDUptimeGetOperation:           []string{},
	APIV4ComponentMovePostOperation:              []string{},
	APIV4ComponentPostOperation:                  []string{},
	APIV4ComponentPutOperation:                   []string{},
	APIV4ComponentSetstatusPostOperation:         []string{},
	APIV4ComponentsGetOperation:                  []string{},
	APIV4ComponentsHistoryGetOperation:           []string{},
	APIV4ComponentsHistoryGroupIDGetOperation:    []string{},
	APIV4ComponentsHistoryIncidentIDGetOperation: []string{},
	APIV4ComponentsPostOperation:                 []string{},
	APIV4ComponentsUptimeGetOperation:            []string{},
	APIV4ContenttemplateGetOperation:             []string{},
	APIV4ContenttemplateIDDeleteOperation:        []string{},
	APIV4ContenttemplateIDGetOperation:           []string{},
	APIV4ContenttemplatePostOperation:            []string{},
	APIV4ContenttemplatePutOperation:             []string{},
	APIV4GroupIDDeleteOperation:                  []string{},
	APIV4GroupIDGetOperation:                     []string{},
	APIV4GroupPostOperation:                      []string{},
	APIV4GroupPutOperation:                       []string{},
	APIV4GroupactionDeleteOperation:              []string{},
	APIV4GroupactionPostOperation:                []string{},
	APIV4GroupcomponentsIDGetOperation:           []string{},
	APIV4GroupcomponentsIDPutOperation:           []string{},
	APIV4GroupincidentsIDGetOperation:            []string{},
	APIV4GroupincidentsIDPutOperation:            []string{},
	APIV4GroupsPostOperation:                     []string{},
	APIV4GroupsubscriptionsIDGetOperation:        []string{},
	APIV4GroupsubscriptionsIDPutOperation:        []string{},
	APIV4IncidentIDDeleteOperation:               []string{},
	APIV4IncidentIDGetOperation:                  []string{},
	APIV4IncidentPostOperation:                   []string{},
	APIV4IncidentPutOperation:                    []string{},
	APIV4IncidentQueuePostOperation:              []string{},
	APIV4IncidentsPostOperation:                  []string{},
	APIV4IncidentupdateIDDeleteOperation:         []string{},
	APIV4MetricDeleteOperation:                   []string{},
	APIV4MetricPostOperation:                     []string{},
	APIV4MetricsPostOperation:                    []string{},
	APIV4PageIDGetOperation:                      []string{},
	APIV4PagePostOperation:                       []string{},
	APIV4PagePutOperation:                        []string{},
	APIV4PageStatusGetOperation:                  []string{},
	APIV4PagesPostOperation:                      []string{},
	APIV4PublicstatuspagesGetOperation:           []string{},
	APIV4SubscriberIDDeleteOperation:             []string{},
	APIV4SubscriberIDGetOperation:                []string{},
	APIV4SubscriberIDReinvitePostOperation:       []string{},
	APIV4SubscriberPostOperation:                 []string{},
	APIV4SubscriberPutOperation:                  []string{},
	APIV4SubscribersPostOperation:                []string{},
	APIV4SubscribersPutOperation:                 []string{},
	APIV4SubscribersSearchPostOperation:          []string{},
	APIV4UserDeleteOperation:                     []string{},
	APIV4UserIDGetOperation:                      []string{},
	APIV4UserPostOperation:                       []string{},
	APIV4UserPutOperation:                        []string{},
	APIV4UsersPostOperation:                      []string{},
	PostApiv4imageuploadOperation:                []string{},
}

// GetRolesForBearer returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearer(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearer(operation string) []string {
	roles, ok := operationRolesBearer[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Bearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearer[operationName]
	rctx, err := s.sec.HandleBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Bearer provides Bearer security value.
	// Put **_ONLY_** your JWT Bearer token on textbox below!.
	Bearer(ctx context.Context, operationName OperationName) (Bearer, error)
}

func (s *Client) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
