// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// API4meAppPost implements POST /api/4me/app operation.
	//
	// POST /api/4me/app
	API4meAppPost(ctx context.Context, req OptAPI4meAppPostReq) (API4meAppPostRes, error)
	// API4meConfigPost implements POST /api/4me/config operation.
	//
	// POST /api/4me/config
	API4meConfigPost(ctx context.Context, req API4meConfigPostReq) error
	// APIAuthenticatePost implements POST /api/authenticate operation.
	//
	// Get Token.
	//
	// POST /api/authenticate
	APIAuthenticatePost(ctx context.Context, req OptAPIAuthenticatePostReq) (APIAuthenticatePostRes, error)
	// APIRefreshPost implements POST /api/refresh operation.
	//
	// Refresh Token.
	//
	// POST /api/refresh
	APIRefreshPost(ctx context.Context, req OptAPIRefreshPostReq) (*APIRefreshPostOK, error)
	// APIV1ComponentsGet implements GET /api/v1/components operation.
	//
	// GET /api/v1/components
	APIV1ComponentsGet(ctx context.Context) (APIV1ComponentsGetRes, error)
	// APIV1ComponentsPost implements POST /api/v1/components operation.
	//
	// POST /api/v1/components
	APIV1ComponentsPost(ctx context.Context, req OptAPIV1ComponentsPostReq) (APIV1ComponentsPostRes, error)
	// APIV1ComponentsPut implements PUT /api/v1/components operation.
	//
	// PUT /api/v1/components
	APIV1ComponentsPut(ctx context.Context, req OptAPIV1ComponentsPutReq, params APIV1ComponentsPutParams) (APIV1ComponentsPutRes, error)
	// APIV1IncidentsGet implements GET /api/v1/incidents operation.
	//
	// GET /api/v1/incidents
	APIV1IncidentsGet(ctx context.Context, params APIV1IncidentsGetParams) (APIV1IncidentsGetRes, error)
	// APIV1IncidentsUpdatesPost implements POST /api/v1/incidents/updates operation.
	//
	// POST /api/v1/incidents/updates
	APIV1IncidentsUpdatesPost(ctx context.Context, req OptAPIV1IncidentsUpdatesPostReq) (APIV1IncidentsUpdatesPostRes, error)
	// APIV1TokenPost implements POST /api/v1/token operation.
	//
	// Get authorization token for v2.
	//
	// POST /api/v1/token
	APIV1TokenPost(ctx context.Context, req OptAPIV1TokenPostReq) (APIV1TokenPostRes, error)
	// APIV4BulkgroupactionDelete implements DELETE /api/v4/bulkgroupaction operation.
	//
	// Remove From Many Groups.
	//
	// DELETE /api/v4/bulkgroupaction
	APIV4BulkgroupactionDelete(ctx context.Context, req []APIV4BulkgroupactionDeleteReqItem) (APIV4BulkgroupactionDeleteRes, error)
	// APIV4BulkgroupactionPost implements POST /api/v4/bulkgroupaction operation.
	//
	// Add To Many Groups.
	//
	// POST /api/v4/bulkgroupaction
	APIV4BulkgroupactionPost(ctx context.Context, req []APIV4BulkgroupactionPostReqItem) (APIV4BulkgroupactionPostRes, error)
	// APIV4BulkgroupsDelete implements DELETE /api/v4/bulkgroups operation.
	//
	// Bulk Delete Groups.
	//
	// DELETE /api/v4/bulkgroups
	APIV4BulkgroupsDelete(ctx context.Context, req APIV4BulkgroupsDeleteReq) (APIV4BulkgroupsDeleteRes, error)
	// APIV4BulkgroupsPost implements POST /api/v4/bulkgroups operation.
	//
	// Bulk Create Groups.
	//
	// POST /api/v4/bulkgroups
	APIV4BulkgroupsPost(ctx context.Context, req []string) (APIV4BulkgroupsPostRes, error)
	// APIV4ComponentDelete implements DELETE /api/v4/component operation.
	//
	// Delete Component.
	//
	// DELETE /api/v4/component
	APIV4ComponentDelete(ctx context.Context, params APIV4ComponentDeleteParams) (APIV4ComponentDeleteRes, error)
	// APIV4ComponentIDGet implements GET /api/v4/component/{id} operation.
	//
	// Get Component.
	//
	// GET /api/v4/component/{id}
	APIV4ComponentIDGet(ctx context.Context, params APIV4ComponentIDGetParams) (APIV4ComponentIDGetRes, error)
	// APIV4ComponentIDHistoryGet implements GET /api/v4/component/{id}/history operation.
	//
	// Get Component History.
	//
	// GET /api/v4/component/{id}/history
	APIV4ComponentIDHistoryGet(ctx context.Context, params APIV4ComponentIDHistoryGetParams) (APIV4ComponentIDHistoryGetRes, error)
	// APIV4ComponentIDUptimeGet implements GET /api/v4/component/{id}/uptime operation.
	//
	// Get Component Uptime.
	//
	// GET /api/v4/component/{id}/uptime
	APIV4ComponentIDUptimeGet(ctx context.Context, params APIV4ComponentIDUptimeGetParams) (APIV4ComponentIDUptimeGetRes, error)
	// APIV4ComponentMovePost implements POST /api/v4/component/move operation.
	//
	// Move Component.
	//
	// POST /api/v4/component/move
	APIV4ComponentMovePost(ctx context.Context, req OptAPIV4ComponentMovePostReq) (APIV4ComponentMovePostRes, error)
	// APIV4ComponentPost implements POST /api/v4/component operation.
	//
	// Create Component.
	//
	// POST /api/v4/component
	APIV4ComponentPost(ctx context.Context, req OptAPIV4ComponentPostReq) (APIV4ComponentPostRes, error)
	// APIV4ComponentPut implements PUT /api/v4/component operation.
	//
	// Update Component.
	//
	// PUT /api/v4/component
	APIV4ComponentPut(ctx context.Context, req OptAPIV4ComponentPutReq) (APIV4ComponentPutRes, error)
	// APIV4ComponentSetstatusPost implements POST /api/v4/component/setstatus operation.
	//
	// Set Component Status.
	//
	// POST /api/v4/component/setstatus
	APIV4ComponentSetstatusPost(ctx context.Context, req OptAPIV4ComponentSetstatusPostReq) (APIV4ComponentSetstatusPostRes, error)
	// APIV4ComponentsGet implements GET /api/v4/components operation.
	//
	// Get All Components.
	//
	// GET /api/v4/components
	APIV4ComponentsGet(ctx context.Context) (APIV4ComponentsGetRes, error)
	// APIV4ComponentsHistoryGet implements GET /api/v4/components/history operation.
	//
	// Get Components History.
	//
	// GET /api/v4/components/history
	APIV4ComponentsHistoryGet(ctx context.Context, params APIV4ComponentsHistoryGetParams) (APIV4ComponentsHistoryGetRes, error)
	// APIV4ComponentsHistoryGroupIDGet implements GET /api/v4/components/history/group/{id} operation.
	//
	// Get Component History for a group.
	//
	// GET /api/v4/components/history/group/{id}
	APIV4ComponentsHistoryGroupIDGet(ctx context.Context, params APIV4ComponentsHistoryGroupIDGetParams) (APIV4ComponentsHistoryGroupIDGetRes, error)
	// APIV4ComponentsHistoryIncidentIDGet implements GET /api/v4/components/history/incident/{id} operation.
	//
	// Get Component History for an incident.
	//
	// GET /api/v4/components/history/incident/{id}
	APIV4ComponentsHistoryIncidentIDGet(ctx context.Context, params APIV4ComponentsHistoryIncidentIDGetParams) (APIV4ComponentsHistoryIncidentIDGetRes, error)
	// APIV4ComponentsPost implements POST /api/v4/components operation.
	//
	// Search Components.
	//
	// POST /api/v4/components
	APIV4ComponentsPost(ctx context.Context, req OptAPIV4ComponentsPostReq) (APIV4ComponentsPostRes, error)
	// APIV4ComponentsUptimeGet implements GET /api/v4/components/uptime operation.
	//
	// Get All Components Uptime.
	//
	// GET /api/v4/components/uptime
	APIV4ComponentsUptimeGet(ctx context.Context, params APIV4ComponentsUptimeGetParams) (APIV4ComponentsUptimeGetRes, error)
	// APIV4ContenttemplateGet implements GET /api/v4/contenttemplate operation.
	//
	// Get All Content Templates.
	//
	// GET /api/v4/contenttemplate
	APIV4ContenttemplateGet(ctx context.Context) (APIV4ContenttemplateGetRes, error)
	// APIV4ContenttemplateIDDelete implements DELETE /api/v4/contenttemplate/{id} operation.
	//
	// Delete Content Template.
	//
	// DELETE /api/v4/contenttemplate/{id}
	APIV4ContenttemplateIDDelete(ctx context.Context, params APIV4ContenttemplateIDDeleteParams) (APIV4ContenttemplateIDDeleteRes, error)
	// APIV4ContenttemplateIDGet implements GET /api/v4/contenttemplate/{id} operation.
	//
	// Get Content Template.
	//
	// GET /api/v4/contenttemplate/{id}
	APIV4ContenttemplateIDGet(ctx context.Context, params APIV4ContenttemplateIDGetParams) (APIV4ContenttemplateIDGetRes, error)
	// APIV4ContenttemplatePost implements POST /api/v4/contenttemplate operation.
	//
	// Create Content Template.
	//
	// POST /api/v4/contenttemplate
	APIV4ContenttemplatePost(ctx context.Context, req OptAPIV4ContenttemplatePostReq) (APIV4ContenttemplatePostRes, error)
	// APIV4ContenttemplatePut implements PUT /api/v4/contenttemplate operation.
	//
	// Update Content Template.
	//
	// PUT /api/v4/contenttemplate
	APIV4ContenttemplatePut(ctx context.Context, req OptAPIV4ContenttemplatePutReq) (APIV4ContenttemplatePutRes, error)
	// APIV4GroupIDDelete implements DELETE /api/v4/group/{id} operation.
	//
	// Delete Group.
	//
	// DELETE /api/v4/group/{id}
	APIV4GroupIDDelete(ctx context.Context, params APIV4GroupIDDeleteParams) (APIV4GroupIDDeleteRes, error)
	// APIV4GroupIDGet implements GET /api/v4/group/{id} operation.
	//
	// Get Group.
	//
	// GET /api/v4/group/{id}
	APIV4GroupIDGet(ctx context.Context, params APIV4GroupIDGetParams) (APIV4GroupIDGetRes, error)
	// APIV4GroupPost implements POST /api/v4/group operation.
	//
	// Create Group.
	//
	// POST /api/v4/group
	APIV4GroupPost(ctx context.Context, req OptAPIV4GroupPostReq) (APIV4GroupPostRes, error)
	// APIV4GroupPut implements PUT /api/v4/group operation.
	//
	// Update Group.
	//
	// PUT /api/v4/group
	APIV4GroupPut(ctx context.Context, req OptAPIV4GroupPutReq) (APIV4GroupPutRes, error)
	// APIV4GroupactionDelete implements DELETE /api/v4/groupaction operation.
	//
	// Remove from Group.
	//
	// DELETE /api/v4/groupaction
	APIV4GroupactionDelete(ctx context.Context, req OptAPIV4GroupactionDeleteReq) (APIV4GroupactionDeleteRes, error)
	// APIV4GroupactionPost implements POST /api/v4/groupaction operation.
	//
	// Add to Group.
	//
	// POST /api/v4/groupaction
	APIV4GroupactionPost(ctx context.Context, req OptAPIV4GroupactionPostReq) (APIV4GroupactionPostRes, error)
	// APIV4GroupcomponentsIDGet implements GET /api/v4/groupcomponents/{id} operation.
	//
	// Get Group Components.
	//
	// GET /api/v4/groupcomponents/{id}
	APIV4GroupcomponentsIDGet(ctx context.Context, params APIV4GroupcomponentsIDGetParams) (APIV4GroupcomponentsIDGetRes, error)
	// APIV4GroupcomponentsIDPut implements PUT /api/v4/groupcomponents/{id} operation.
	//
	// Put Group Components.
	//
	// PUT /api/v4/groupcomponents/{id}
	APIV4GroupcomponentsIDPut(ctx context.Context, req APIV4GroupcomponentsIDPutReq, params APIV4GroupcomponentsIDPutParams) (APIV4GroupcomponentsIDPutRes, error)
	// APIV4GroupincidentsIDGet implements GET /api/v4/groupincidents/{id} operation.
	//
	// Get Group Incidents.
	//
	// GET /api/v4/groupincidents/{id}
	APIV4GroupincidentsIDGet(ctx context.Context, params APIV4GroupincidentsIDGetParams) (APIV4GroupincidentsIDGetRes, error)
	// APIV4GroupincidentsIDPut implements PUT /api/v4/groupincidents/{id} operation.
	//
	// Put Group Incidents.
	//
	// PUT /api/v4/groupincidents/{id}
	APIV4GroupincidentsIDPut(ctx context.Context, req APIV4GroupincidentsIDPutReq, params APIV4GroupincidentsIDPutParams) (APIV4GroupincidentsIDPutRes, error)
	// APIV4GroupsPost implements POST /api/v4/groups operation.
	//
	// Search Groups.
	//
	// POST /api/v4/groups
	APIV4GroupsPost(ctx context.Context, req OptAPIV4GroupsPostReq) (APIV4GroupsPostRes, error)
	// APIV4GroupsubscriptionsIDGet implements GET /api/v4/groupsubscriptions/{id} operation.
	//
	// Get Group Subscriptions.
	//
	// GET /api/v4/groupsubscriptions/{id}
	APIV4GroupsubscriptionsIDGet(ctx context.Context, params APIV4GroupsubscriptionsIDGetParams) (APIV4GroupsubscriptionsIDGetRes, error)
	// APIV4GroupsubscriptionsIDPut implements PUT /api/v4/groupsubscriptions/{id} operation.
	//
	// Put Group Subscriptions.
	//
	// PUT /api/v4/groupsubscriptions/{id}
	APIV4GroupsubscriptionsIDPut(ctx context.Context, req APIV4GroupsubscriptionsIDPutReq, params APIV4GroupsubscriptionsIDPutParams) (APIV4GroupsubscriptionsIDPutRes, error)
	// APIV4IncidentIDDelete implements DELETE /api/v4/incident/{id} operation.
	//
	// Delete Incident.
	//
	// DELETE /api/v4/incident/{id}
	APIV4IncidentIDDelete(ctx context.Context, params APIV4IncidentIDDeleteParams) (APIV4IncidentIDDeleteRes, error)
	// APIV4IncidentIDGet implements GET /api/v4/incident/{id} operation.
	//
	// Get Incident.
	//
	// GET /api/v4/incident/{id}
	APIV4IncidentIDGet(ctx context.Context, params APIV4IncidentIDGetParams) (APIV4IncidentIDGetRes, error)
	// APIV4IncidentPost implements POST /api/v4/incident operation.
	//
	// Create Incident.
	//
	// POST /api/v4/incident
	APIV4IncidentPost(ctx context.Context, req OptAPIV4IncidentPostReq) (APIV4IncidentPostRes, error)
	// APIV4IncidentPut implements PUT /api/v4/incident operation.
	//
	// Update Incident.
	//
	// PUT /api/v4/incident
	APIV4IncidentPut(ctx context.Context, req OptAPIV4IncidentPutReq) (APIV4IncidentPutRes, error)
	// APIV4IncidentQueuePost implements POST /api/v4/incident/queue operation.
	//
	// Create Incident.
	//
	// POST /api/v4/incident/queue
	APIV4IncidentQueuePost(ctx context.Context, req OptAPIV4IncidentQueuePostReq) (APIV4IncidentQueuePostRes, error)
	// APIV4IncidentsPost implements POST /api/v4/incidents operation.
	//
	// Search Incidents.
	//
	// POST /api/v4/incidents
	APIV4IncidentsPost(ctx context.Context, req OptAPIV4IncidentsPostReq) (APIV4IncidentsPostRes, error)
	// APIV4IncidentupdateIDDelete implements DELETE /api/v4/incidentupdate/{id} operation.
	//
	// Delete Incident Update.
	//
	// DELETE /api/v4/incidentupdate/{id}
	APIV4IncidentupdateIDDelete(ctx context.Context, params APIV4IncidentupdateIDDeleteParams) (APIV4IncidentupdateIDDeleteRes, error)
	// APIV4MetricDelete implements DELETE /api/v4/metric operation.
	//
	// Delete Metric Data.
	//
	// DELETE /api/v4/metric
	APIV4MetricDelete(ctx context.Context, req OptAPIV4MetricDeleteReq) (APIV4MetricDeleteRes, error)
	// APIV4MetricPost implements POST /api/v4/metric operation.
	//
	// Create Metric Data.
	//
	// POST /api/v4/metric
	APIV4MetricPost(ctx context.Context, req OptAPIV4MetricPostReq) (APIV4MetricPostRes, error)
	// APIV4MetricsPost implements POST /api/v4/metrics operation.
	//
	// Search Metrics.
	//
	// POST /api/v4/metrics
	APIV4MetricsPost(ctx context.Context, req OptAPIV4MetricsPostReq) (APIV4MetricsPostRes, error)
	// APIV4PageIDGet implements GET /api/v4/page/{id} operation.
	//
	// Get Page.
	//
	// GET /api/v4/page/{id}
	APIV4PageIDGet(ctx context.Context, params APIV4PageIDGetParams) (APIV4PageIDGetRes, error)
	// APIV4PagePost implements POST /api/v4/page operation.
	//
	// Create Page.
	//
	// POST /api/v4/page
	APIV4PagePost(ctx context.Context, req OptAPIV4PagePostReq) (APIV4PagePostRes, error)
	// APIV4PagePut implements PUT /api/v4/page operation.
	//
	// Update Page.
	//
	// PUT /api/v4/page
	APIV4PagePut(ctx context.Context, req OptAPIV4PagePutReq) (APIV4PagePutRes, error)
	// APIV4PageStatusGet implements GET /api/v4/page/status operation.
	//
	// Get Page Status.
	//
	// GET /api/v4/page/status
	APIV4PageStatusGet(ctx context.Context) (APIV4PageStatusGetRes, error)
	// APIV4PagesPost implements POST /api/v4/pages operation.
	//
	// Search Pages.
	//
	// POST /api/v4/pages
	APIV4PagesPost(ctx context.Context, req OptAPIV4PagesPostReq) (APIV4PagesPostRes, error)
	// APIV4PublicstatuspagesGet implements GET /api/v4/publicstatuspages operation.
	//
	// Search public pages as an asynchronous operation.
	//
	// GET /api/v4/publicstatuspages
	APIV4PublicstatuspagesGet(ctx context.Context, params APIV4PublicstatuspagesGetParams) (APIV4PublicstatuspagesGetRes, error)
	// APIV4SubscriberIDDelete implements DELETE /api/v4/subscriber/{id} operation.
	//
	// Delete Subscriber.
	//
	// DELETE /api/v4/subscriber/{id}
	APIV4SubscriberIDDelete(ctx context.Context, params APIV4SubscriberIDDeleteParams) (APIV4SubscriberIDDeleteRes, error)
	// APIV4SubscriberIDGet implements GET /api/v4/subscriber/{id} operation.
	//
	// Get Subscriber.
	//
	// GET /api/v4/subscriber/{id}
	APIV4SubscriberIDGet(ctx context.Context, params APIV4SubscriberIDGetParams) (APIV4SubscriberIDGetRes, error)
	// APIV4SubscriberIDReinvitePost implements POST /api/v4/subscriber/{id}/reinvite operation.
	//
	// Re-Invite Subscriber.
	//
	// POST /api/v4/subscriber/{id}/reinvite
	APIV4SubscriberIDReinvitePost(ctx context.Context, params APIV4SubscriberIDReinvitePostParams) (APIV4SubscriberIDReinvitePostRes, error)
	// APIV4SubscriberPost implements POST /api/v4/subscriber operation.
	//
	// Create Subscriber.
	//
	// POST /api/v4/subscriber
	APIV4SubscriberPost(ctx context.Context, req OptAPIV4SubscriberPostReq) (APIV4SubscriberPostRes, error)
	// APIV4SubscriberPut implements PUT /api/v4/subscriber operation.
	//
	// Update Subscriber.
	//
	// PUT /api/v4/subscriber
	APIV4SubscriberPut(ctx context.Context, req OptAPIV4SubscriberPutReq) (APIV4SubscriberPutRes, error)
	// APIV4SubscribersPost implements POST /api/v4/subscribers operation.
	//
	// Create Subscribers.
	//
	// POST /api/v4/subscribers
	APIV4SubscribersPost(ctx context.Context, req []APIV4SubscribersPostReqItem) (APIV4SubscribersPostRes, error)
	// APIV4SubscribersPut implements PUT /api/v4/subscribers operation.
	//
	// Update Subscribers.
	//
	// PUT /api/v4/subscribers
	APIV4SubscribersPut(ctx context.Context, req []APIV4SubscribersPutReqItem) (APIV4SubscribersPutRes, error)
	// APIV4SubscribersSearchPost implements POST /api/v4/subscribers/search operation.
	//
	// Search Subscribers.
	//
	// POST /api/v4/subscribers/search
	APIV4SubscribersSearchPost(ctx context.Context, req OptAPIV4SubscribersSearchPostReq) (APIV4SubscribersSearchPostRes, error)
	// APIV4UserDelete implements DELETE /api/v4/user operation.
	//
	// Delete User.
	//
	// DELETE /api/v4/user
	APIV4UserDelete(ctx context.Context, params APIV4UserDeleteParams) (APIV4UserDeleteRes, error)
	// APIV4UserIDGet implements GET /api/v4/user/{id} operation.
	//
	// Get User.
	//
	// GET /api/v4/user/{id}
	APIV4UserIDGet(ctx context.Context, params APIV4UserIDGetParams) (APIV4UserIDGetRes, error)
	// APIV4UserPost implements POST /api/v4/user operation.
	//
	// Create User.
	//
	// POST /api/v4/user
	APIV4UserPost(ctx context.Context, req OptAPIV4UserPostReq) (APIV4UserPostRes, error)
	// APIV4UserPut implements PUT /api/v4/user operation.
	//
	// Update User.
	//
	// PUT /api/v4/user
	APIV4UserPut(ctx context.Context, req OptAPIV4UserPutReq) (APIV4UserPutRes, error)
	// APIV4UsersPost implements POST /api/v4/users operation.
	//
	// Search Users.
	//
	// POST /api/v4/users
	APIV4UsersPost(ctx context.Context, req OptAPIV4UsersPostReq) (APIV4UsersPostRes, error)
	// PostApiv4imageupload implements post_apiv4imageupload operation.
	//
	// POST /api/v4/image/upload
	PostApiv4imageupload(ctx context.Context, req OptPostApiv4imageuploadReq) (PostApiv4imageuploadRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
