// Code generated by ogen, DO NOT EDIT.

package statuscast

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// API4meAppPost implements POST /api/4me/app operation.
//
// POST /api/4me/app
func (UnimplementedHandler) API4meAppPost(ctx context.Context, req OptAPI4meAppPostReq) (r API4meAppPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// API4meConfigPost implements POST /api/4me/config operation.
//
// POST /api/4me/config
func (UnimplementedHandler) API4meConfigPost(ctx context.Context, req API4meConfigPostReq) error {
	return ht.ErrNotImplemented
}

// APIAuthenticatePost implements POST /api/authenticate operation.
//
// Get Token.
//
// POST /api/authenticate
func (UnimplementedHandler) APIAuthenticatePost(ctx context.Context, req OptAPIAuthenticatePostReq) (r APIAuthenticatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRefreshPost implements POST /api/refresh operation.
//
// Refresh Token.
//
// POST /api/refresh
func (UnimplementedHandler) APIRefreshPost(ctx context.Context, req OptAPIRefreshPostReq) (r *APIRefreshPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ComponentsGet implements GET /api/v1/components operation.
//
// GET /api/v1/components
func (UnimplementedHandler) APIV1ComponentsGet(ctx context.Context) (r APIV1ComponentsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ComponentsPost implements POST /api/v1/components operation.
//
// POST /api/v1/components
func (UnimplementedHandler) APIV1ComponentsPost(ctx context.Context, req OptAPIV1ComponentsPostReq) (r APIV1ComponentsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1ComponentsPut implements PUT /api/v1/components operation.
//
// PUT /api/v1/components
func (UnimplementedHandler) APIV1ComponentsPut(ctx context.Context, req OptAPIV1ComponentsPutReq, params APIV1ComponentsPutParams) (r APIV1ComponentsPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1IncidentsGet implements GET /api/v1/incidents operation.
//
// GET /api/v1/incidents
func (UnimplementedHandler) APIV1IncidentsGet(ctx context.Context, params APIV1IncidentsGetParams) (r APIV1IncidentsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1IncidentsUpdatesPost implements POST /api/v1/incidents/updates operation.
//
// POST /api/v1/incidents/updates
func (UnimplementedHandler) APIV1IncidentsUpdatesPost(ctx context.Context, req OptAPIV1IncidentsUpdatesPostReq) (r APIV1IncidentsUpdatesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1TokenPost implements POST /api/v1/token operation.
//
// Get authorization token for v2.
//
// POST /api/v1/token
func (UnimplementedHandler) APIV1TokenPost(ctx context.Context, req OptAPIV1TokenPostReq) (r APIV1TokenPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4BulkgroupactionDelete implements DELETE /api/v4/bulkgroupaction operation.
//
// Remove From Many Groups.
//
// DELETE /api/v4/bulkgroupaction
func (UnimplementedHandler) APIV4BulkgroupactionDelete(ctx context.Context, req []APIV4BulkgroupactionDeleteReqItem) (r APIV4BulkgroupactionDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4BulkgroupactionPost implements POST /api/v4/bulkgroupaction operation.
//
// Add To Many Groups.
//
// POST /api/v4/bulkgroupaction
func (UnimplementedHandler) APIV4BulkgroupactionPost(ctx context.Context, req []APIV4BulkgroupactionPostReqItem) (r APIV4BulkgroupactionPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4BulkgroupsDelete implements DELETE /api/v4/bulkgroups operation.
//
// Bulk Delete Groups.
//
// DELETE /api/v4/bulkgroups
func (UnimplementedHandler) APIV4BulkgroupsDelete(ctx context.Context, req APIV4BulkgroupsDeleteReq) (r APIV4BulkgroupsDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4BulkgroupsPost implements POST /api/v4/bulkgroups operation.
//
// Bulk Create Groups.
//
// POST /api/v4/bulkgroups
func (UnimplementedHandler) APIV4BulkgroupsPost(ctx context.Context, req []string) (r APIV4BulkgroupsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentDelete implements DELETE /api/v4/component operation.
//
// Delete Component.
//
// DELETE /api/v4/component
func (UnimplementedHandler) APIV4ComponentDelete(ctx context.Context, params APIV4ComponentDeleteParams) (r APIV4ComponentDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentIDGet implements GET /api/v4/component/{id} operation.
//
// Get Component.
//
// GET /api/v4/component/{id}
func (UnimplementedHandler) APIV4ComponentIDGet(ctx context.Context, params APIV4ComponentIDGetParams) (r APIV4ComponentIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentIDHistoryGet implements GET /api/v4/component/{id}/history operation.
//
// Get Component History.
//
// GET /api/v4/component/{id}/history
func (UnimplementedHandler) APIV4ComponentIDHistoryGet(ctx context.Context, params APIV4ComponentIDHistoryGetParams) (r APIV4ComponentIDHistoryGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentIDUptimeGet implements GET /api/v4/component/{id}/uptime operation.
//
// Get Component Uptime.
//
// GET /api/v4/component/{id}/uptime
func (UnimplementedHandler) APIV4ComponentIDUptimeGet(ctx context.Context, params APIV4ComponentIDUptimeGetParams) (r APIV4ComponentIDUptimeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentMovePost implements POST /api/v4/component/move operation.
//
// Move Component.
//
// POST /api/v4/component/move
func (UnimplementedHandler) APIV4ComponentMovePost(ctx context.Context, req OptAPIV4ComponentMovePostReq) (r APIV4ComponentMovePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentPost implements POST /api/v4/component operation.
//
// Create Component.
//
// POST /api/v4/component
func (UnimplementedHandler) APIV4ComponentPost(ctx context.Context, req OptAPIV4ComponentPostReq) (r APIV4ComponentPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentPut implements PUT /api/v4/component operation.
//
// Update Component.
//
// PUT /api/v4/component
func (UnimplementedHandler) APIV4ComponentPut(ctx context.Context, req OptAPIV4ComponentPutReq) (r APIV4ComponentPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentSetstatusPost implements POST /api/v4/component/setstatus operation.
//
// Set Component Status.
//
// POST /api/v4/component/setstatus
func (UnimplementedHandler) APIV4ComponentSetstatusPost(ctx context.Context, req OptAPIV4ComponentSetstatusPostReq) (r APIV4ComponentSetstatusPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsGet implements GET /api/v4/components operation.
//
// Get All Components.
//
// GET /api/v4/components
func (UnimplementedHandler) APIV4ComponentsGet(ctx context.Context) (r APIV4ComponentsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsHistoryGet implements GET /api/v4/components/history operation.
//
// Get Components History.
//
// GET /api/v4/components/history
func (UnimplementedHandler) APIV4ComponentsHistoryGet(ctx context.Context, params APIV4ComponentsHistoryGetParams) (r APIV4ComponentsHistoryGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsHistoryGroupIDGet implements GET /api/v4/components/history/group/{id} operation.
//
// Get Component History for a group.
//
// GET /api/v4/components/history/group/{id}
func (UnimplementedHandler) APIV4ComponentsHistoryGroupIDGet(ctx context.Context, params APIV4ComponentsHistoryGroupIDGetParams) (r APIV4ComponentsHistoryGroupIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsHistoryIncidentIDGet implements GET /api/v4/components/history/incident/{id} operation.
//
// Get Component History for an incident.
//
// GET /api/v4/components/history/incident/{id}
func (UnimplementedHandler) APIV4ComponentsHistoryIncidentIDGet(ctx context.Context, params APIV4ComponentsHistoryIncidentIDGetParams) (r APIV4ComponentsHistoryIncidentIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsPost implements POST /api/v4/components operation.
//
// Search Components.
//
// POST /api/v4/components
func (UnimplementedHandler) APIV4ComponentsPost(ctx context.Context, req OptAPIV4ComponentsPostReq) (r APIV4ComponentsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ComponentsUptimeGet implements GET /api/v4/components/uptime operation.
//
// Get All Components Uptime.
//
// GET /api/v4/components/uptime
func (UnimplementedHandler) APIV4ComponentsUptimeGet(ctx context.Context, params APIV4ComponentsUptimeGetParams) (r APIV4ComponentsUptimeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ContenttemplateGet implements GET /api/v4/contenttemplate operation.
//
// Get All Content Templates.
//
// GET /api/v4/contenttemplate
func (UnimplementedHandler) APIV4ContenttemplateGet(ctx context.Context) (r APIV4ContenttemplateGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ContenttemplateIDDelete implements DELETE /api/v4/contenttemplate/{id} operation.
//
// Delete Content Template.
//
// DELETE /api/v4/contenttemplate/{id}
func (UnimplementedHandler) APIV4ContenttemplateIDDelete(ctx context.Context, params APIV4ContenttemplateIDDeleteParams) (r APIV4ContenttemplateIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ContenttemplateIDGet implements GET /api/v4/contenttemplate/{id} operation.
//
// Get Content Template.
//
// GET /api/v4/contenttemplate/{id}
func (UnimplementedHandler) APIV4ContenttemplateIDGet(ctx context.Context, params APIV4ContenttemplateIDGetParams) (r APIV4ContenttemplateIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ContenttemplatePost implements POST /api/v4/contenttemplate operation.
//
// Create Content Template.
//
// POST /api/v4/contenttemplate
func (UnimplementedHandler) APIV4ContenttemplatePost(ctx context.Context, req OptAPIV4ContenttemplatePostReq) (r APIV4ContenttemplatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4ContenttemplatePut implements PUT /api/v4/contenttemplate operation.
//
// Update Content Template.
//
// PUT /api/v4/contenttemplate
func (UnimplementedHandler) APIV4ContenttemplatePut(ctx context.Context, req OptAPIV4ContenttemplatePutReq) (r APIV4ContenttemplatePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupIDDelete implements DELETE /api/v4/group/{id} operation.
//
// Delete Group.
//
// DELETE /api/v4/group/{id}
func (UnimplementedHandler) APIV4GroupIDDelete(ctx context.Context, params APIV4GroupIDDeleteParams) (r APIV4GroupIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupIDGet implements GET /api/v4/group/{id} operation.
//
// Get Group.
//
// GET /api/v4/group/{id}
func (UnimplementedHandler) APIV4GroupIDGet(ctx context.Context, params APIV4GroupIDGetParams) (r APIV4GroupIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupPost implements POST /api/v4/group operation.
//
// Create Group.
//
// POST /api/v4/group
func (UnimplementedHandler) APIV4GroupPost(ctx context.Context, req OptAPIV4GroupPostReq) (r APIV4GroupPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupPut implements PUT /api/v4/group operation.
//
// Update Group.
//
// PUT /api/v4/group
func (UnimplementedHandler) APIV4GroupPut(ctx context.Context, req OptAPIV4GroupPutReq) (r APIV4GroupPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupactionDelete implements DELETE /api/v4/groupaction operation.
//
// Remove from Group.
//
// DELETE /api/v4/groupaction
func (UnimplementedHandler) APIV4GroupactionDelete(ctx context.Context, req OptAPIV4GroupactionDeleteReq) (r APIV4GroupactionDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupactionPost implements POST /api/v4/groupaction operation.
//
// Add to Group.
//
// POST /api/v4/groupaction
func (UnimplementedHandler) APIV4GroupactionPost(ctx context.Context, req OptAPIV4GroupactionPostReq) (r APIV4GroupactionPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupcomponentsIDGet implements GET /api/v4/groupcomponents/{id} operation.
//
// Get Group Components.
//
// GET /api/v4/groupcomponents/{id}
func (UnimplementedHandler) APIV4GroupcomponentsIDGet(ctx context.Context, params APIV4GroupcomponentsIDGetParams) (r APIV4GroupcomponentsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupcomponentsIDPut implements PUT /api/v4/groupcomponents/{id} operation.
//
// Put Group Components.
//
// PUT /api/v4/groupcomponents/{id}
func (UnimplementedHandler) APIV4GroupcomponentsIDPut(ctx context.Context, req APIV4GroupcomponentsIDPutReq, params APIV4GroupcomponentsIDPutParams) (r APIV4GroupcomponentsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupincidentsIDGet implements GET /api/v4/groupincidents/{id} operation.
//
// Get Group Incidents.
//
// GET /api/v4/groupincidents/{id}
func (UnimplementedHandler) APIV4GroupincidentsIDGet(ctx context.Context, params APIV4GroupincidentsIDGetParams) (r APIV4GroupincidentsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupincidentsIDPut implements PUT /api/v4/groupincidents/{id} operation.
//
// Put Group Incidents.
//
// PUT /api/v4/groupincidents/{id}
func (UnimplementedHandler) APIV4GroupincidentsIDPut(ctx context.Context, req APIV4GroupincidentsIDPutReq, params APIV4GroupincidentsIDPutParams) (r APIV4GroupincidentsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupsPost implements POST /api/v4/groups operation.
//
// Search Groups.
//
// POST /api/v4/groups
func (UnimplementedHandler) APIV4GroupsPost(ctx context.Context, req OptAPIV4GroupsPostReq) (r APIV4GroupsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupsubscriptionsIDGet implements GET /api/v4/groupsubscriptions/{id} operation.
//
// Get Group Subscriptions.
//
// GET /api/v4/groupsubscriptions/{id}
func (UnimplementedHandler) APIV4GroupsubscriptionsIDGet(ctx context.Context, params APIV4GroupsubscriptionsIDGetParams) (r APIV4GroupsubscriptionsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4GroupsubscriptionsIDPut implements PUT /api/v4/groupsubscriptions/{id} operation.
//
// Put Group Subscriptions.
//
// PUT /api/v4/groupsubscriptions/{id}
func (UnimplementedHandler) APIV4GroupsubscriptionsIDPut(ctx context.Context, req APIV4GroupsubscriptionsIDPutReq, params APIV4GroupsubscriptionsIDPutParams) (r APIV4GroupsubscriptionsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentIDDelete implements DELETE /api/v4/incident/{id} operation.
//
// Delete Incident.
//
// DELETE /api/v4/incident/{id}
func (UnimplementedHandler) APIV4IncidentIDDelete(ctx context.Context, params APIV4IncidentIDDeleteParams) (r APIV4IncidentIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentIDGet implements GET /api/v4/incident/{id} operation.
//
// Get Incident.
//
// GET /api/v4/incident/{id}
func (UnimplementedHandler) APIV4IncidentIDGet(ctx context.Context, params APIV4IncidentIDGetParams) (r APIV4IncidentIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentPost implements POST /api/v4/incident operation.
//
// Create Incident.
//
// POST /api/v4/incident
func (UnimplementedHandler) APIV4IncidentPost(ctx context.Context, req OptAPIV4IncidentPostReq) (r APIV4IncidentPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentPut implements PUT /api/v4/incident operation.
//
// Update Incident.
//
// PUT /api/v4/incident
func (UnimplementedHandler) APIV4IncidentPut(ctx context.Context, req OptAPIV4IncidentPutReq) (r APIV4IncidentPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentQueuePost implements POST /api/v4/incident/queue operation.
//
// Create Incident.
//
// POST /api/v4/incident/queue
func (UnimplementedHandler) APIV4IncidentQueuePost(ctx context.Context, req OptAPIV4IncidentQueuePostReq) (r APIV4IncidentQueuePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentsPost implements POST /api/v4/incidents operation.
//
// Search Incidents.
//
// POST /api/v4/incidents
func (UnimplementedHandler) APIV4IncidentsPost(ctx context.Context, req OptAPIV4IncidentsPostReq) (r APIV4IncidentsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4IncidentupdateIDDelete implements DELETE /api/v4/incidentupdate/{id} operation.
//
// Delete Incident Update.
//
// DELETE /api/v4/incidentupdate/{id}
func (UnimplementedHandler) APIV4IncidentupdateIDDelete(ctx context.Context, params APIV4IncidentupdateIDDeleteParams) (r APIV4IncidentupdateIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4MetricDelete implements DELETE /api/v4/metric operation.
//
// Delete Metric Data.
//
// DELETE /api/v4/metric
func (UnimplementedHandler) APIV4MetricDelete(ctx context.Context, req OptAPIV4MetricDeleteReq) (r APIV4MetricDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4MetricPost implements POST /api/v4/metric operation.
//
// Create Metric Data.
//
// POST /api/v4/metric
func (UnimplementedHandler) APIV4MetricPost(ctx context.Context, req OptAPIV4MetricPostReq) (r APIV4MetricPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4MetricsPost implements POST /api/v4/metrics operation.
//
// Search Metrics.
//
// POST /api/v4/metrics
func (UnimplementedHandler) APIV4MetricsPost(ctx context.Context, req OptAPIV4MetricsPostReq) (r APIV4MetricsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PageIDGet implements GET /api/v4/page/{id} operation.
//
// Get Page.
//
// GET /api/v4/page/{id}
func (UnimplementedHandler) APIV4PageIDGet(ctx context.Context, params APIV4PageIDGetParams) (r APIV4PageIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PagePost implements POST /api/v4/page operation.
//
// Create Page.
//
// POST /api/v4/page
func (UnimplementedHandler) APIV4PagePost(ctx context.Context, req OptAPIV4PagePostReq) (r APIV4PagePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PagePut implements PUT /api/v4/page operation.
//
// Update Page.
//
// PUT /api/v4/page
func (UnimplementedHandler) APIV4PagePut(ctx context.Context, req OptAPIV4PagePutReq) (r APIV4PagePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PageStatusGet implements GET /api/v4/page/status operation.
//
// Get Page Status.
//
// GET /api/v4/page/status
func (UnimplementedHandler) APIV4PageStatusGet(ctx context.Context) (r APIV4PageStatusGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PagesPost implements POST /api/v4/pages operation.
//
// Search Pages.
//
// POST /api/v4/pages
func (UnimplementedHandler) APIV4PagesPost(ctx context.Context, req OptAPIV4PagesPostReq) (r APIV4PagesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4PublicstatuspagesGet implements GET /api/v4/publicstatuspages operation.
//
// Search public pages as an asynchronous operation.
//
// GET /api/v4/publicstatuspages
func (UnimplementedHandler) APIV4PublicstatuspagesGet(ctx context.Context, params APIV4PublicstatuspagesGetParams) (r APIV4PublicstatuspagesGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscriberIDDelete implements DELETE /api/v4/subscriber/{id} operation.
//
// Delete Subscriber.
//
// DELETE /api/v4/subscriber/{id}
func (UnimplementedHandler) APIV4SubscriberIDDelete(ctx context.Context, params APIV4SubscriberIDDeleteParams) (r APIV4SubscriberIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscriberIDGet implements GET /api/v4/subscriber/{id} operation.
//
// Get Subscriber.
//
// GET /api/v4/subscriber/{id}
func (UnimplementedHandler) APIV4SubscriberIDGet(ctx context.Context, params APIV4SubscriberIDGetParams) (r APIV4SubscriberIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscriberIDReinvitePost implements POST /api/v4/subscriber/{id}/reinvite operation.
//
// Re-Invite Subscriber.
//
// POST /api/v4/subscriber/{id}/reinvite
func (UnimplementedHandler) APIV4SubscriberIDReinvitePost(ctx context.Context, params APIV4SubscriberIDReinvitePostParams) (r APIV4SubscriberIDReinvitePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscriberPost implements POST /api/v4/subscriber operation.
//
// Create Subscriber.
//
// POST /api/v4/subscriber
func (UnimplementedHandler) APIV4SubscriberPost(ctx context.Context, req OptAPIV4SubscriberPostReq) (r APIV4SubscriberPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscriberPut implements PUT /api/v4/subscriber operation.
//
// Update Subscriber.
//
// PUT /api/v4/subscriber
func (UnimplementedHandler) APIV4SubscriberPut(ctx context.Context, req OptAPIV4SubscriberPutReq) (r APIV4SubscriberPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscribersPost implements POST /api/v4/subscribers operation.
//
// Create Subscribers.
//
// POST /api/v4/subscribers
func (UnimplementedHandler) APIV4SubscribersPost(ctx context.Context, req []APIV4SubscribersPostReqItem) (r APIV4SubscribersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscribersPut implements PUT /api/v4/subscribers operation.
//
// Update Subscribers.
//
// PUT /api/v4/subscribers
func (UnimplementedHandler) APIV4SubscribersPut(ctx context.Context, req []APIV4SubscribersPutReqItem) (r APIV4SubscribersPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4SubscribersSearchPost implements POST /api/v4/subscribers/search operation.
//
// Search Subscribers.
//
// POST /api/v4/subscribers/search
func (UnimplementedHandler) APIV4SubscribersSearchPost(ctx context.Context, req OptAPIV4SubscribersSearchPostReq) (r APIV4SubscribersSearchPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4UserDelete implements DELETE /api/v4/user operation.
//
// Delete User.
//
// DELETE /api/v4/user
func (UnimplementedHandler) APIV4UserDelete(ctx context.Context, params APIV4UserDeleteParams) (r APIV4UserDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4UserIDGet implements GET /api/v4/user/{id} operation.
//
// Get User.
//
// GET /api/v4/user/{id}
func (UnimplementedHandler) APIV4UserIDGet(ctx context.Context, params APIV4UserIDGetParams) (r APIV4UserIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4UserPost implements POST /api/v4/user operation.
//
// Create User.
//
// POST /api/v4/user
func (UnimplementedHandler) APIV4UserPost(ctx context.Context, req OptAPIV4UserPostReq) (r APIV4UserPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4UserPut implements PUT /api/v4/user operation.
//
// Update User.
//
// PUT /api/v4/user
func (UnimplementedHandler) APIV4UserPut(ctx context.Context, req OptAPIV4UserPutReq) (r APIV4UserPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV4UsersPost implements POST /api/v4/users operation.
//
// Search Users.
//
// POST /api/v4/users
func (UnimplementedHandler) APIV4UsersPost(ctx context.Context, req OptAPIV4UsersPostReq) (r APIV4UsersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostApiv4imageupload implements post_apiv4imageupload operation.
//
// POST /api/v4/image/upload
func (UnimplementedHandler) PostApiv4imageupload(ctx context.Context, req OptPostApiv4imageuploadReq) (r PostApiv4imageuploadRes, _ error) {
	return r, ht.ErrNotImplemented
}
